### ISSUE TITLE
Serious performance issue because of broken core design

### ISSUE THREAD

**Issue by kof** [Famous/famous#111]
Today I have started to investigate where my application spends cpu cycles. It turns out .commit methods in all classes is the biggest issue.

A simple screen of 6 surfaces and flexible layout takes 5% cpu on iphone 5 based on xcode graph.

It turns out on every animation frame tick engine calls .commit methods of all displayed instances.

This is seriously broken by design! You can't run all the calculations on every frame and this is even without any user interactions.

**Comment by trusktr** [comment]
@michaelobriena @ftripier @dmvaldman Idea: gitter.im

Persistent searchable chat for all.

Have development discussions there. That would be amazing for the community, in my humble opinion.

**Comment by trusktr** [comment]
Are web workers coming into play?

**Comment by trusktr** [comment]
Simple untested idea: Make two loops, an rAF loop, and an Engine loop inside an [inline worker](http://stackoverflow.com/a/19201292/454780). The Engine loop can run freely, limited only by the thread speed. The rAF loop can send element sizes to the worker, and the rAF loop can query the worker for the RenderTree's current matrix3d transforms (a simple array!) at 60fps. 

Already have any plans like this?

**Comment by MylesBorins** [comment]
Closing... check out http://github.com/famous/engine
