### ISSUE TITLE
TouchSync not firing update on Windows Phone

### ISSUE THREAD

**Issue by jaandrews** [Famous/famous#120]
I have a scrolling framework deployed to the mobile version of [Velo Apartments](http://veloapts.com/mobile). It's also currently reachable at https://github.com/BonsaiMediaGroup/veloMobile. I've set up a GenericSync that pulls in scroll and touch syncs (lines 22-25, 49-52, 55-70 of /src/widgets/WorldScroll.js). It works on iphone and android, but does not fire on my Windows Phone (Lumia 1020 running Windows Phone 8.0).

Are pointer events not supported by TouchSync by any chance?

**Comment by MylesBorins** [comment]
closing for now awaiting fix in spartan browser. Please reopen if you like.
