### ISSUE TITLE
Editor recommendations for famo.us ?

### ISSUE THREAD

**Issue by IjzerenHein** [Famous/famous#121]
Hi, I was wondering, do you have any Editor recommendations for famo.us?

Until now, I've been using Brackets (on Mac) for my javascript development. It uses JSLint instead of ESLint, and I'm having a really hard time getting JSLint to behave the same way as the default famo.us ESLint configuration.
I like brackets, but I find it even more important to use the same coding-rules as you use, also for making future pull-requests (so that this doesn't happen anymore: https://github.com/Famous/core/pull/59).

What editors do you guys use (on Mac) ?

**Comment by leogoro** [comment]
Can you leave an example of your brackets config file so that I can try on my end.
