### ISSUE TITLE
Rename Scrollview to ScrollView?

### ISSUE THREAD

**Issue by MajorBreakfast** [Famous/famous#168]
Ya, but I've got to ask because the rest of the industry writes it differently and I'm constantly writing it wrong :)

http://developer.android.com/reference/android/widget/ScrollView.html
https://developer.apple.com/library/ios/documentation/uikit/reference/uiscrollview_class/Reference/UIScrollView.html

**Comment by MylesBorins** [comment]
for now this will probably not land.  Closing
