### ISSUE TITLE
Suggestion: OptionsManager.setOptionsManager

### ISSUE THREAD

**Issue by speigg** [Famous/famous#210]
Akin to `EventHandler.setInputHandler/setOutputHandler(object, handler)`,  ` OptionsManager.setOptionsManager(object, manager)` would mix the following into an `object`: 

`setOptions` =>  `OptionsManager.prototype.setOptions`
`set` =>  `OptionsManager.prototype.set`
`getOptions` =>  `OptionsManager.prototype.getOptions` 
`get` =>  `OptionsManager.prototype.get`

This also avoids api inconsistencies, such as: 

```javascript
// View.prototype.getOptions returns the entire options dictionary
View.prototype.getOptions = function getOptions() {
        return this._optionsManager.value();
};

// But Engine.getOptions takes an id parameter and returns a specific option value
Engine.getOptions = function getOptions() {
        return optionsManager.getOptions.apply(optionsManager, arguments);
};
```

IMO, one of the above two existing methods is a bug. Either `Engine.getOptions` is doing things right, or `View.getOptions` is doing things right, but since they both have the same name, they should both exhibit the same behavior (and they don't). `OptionsManager.setOptionsManager` would help avoid these kinds of mistakes both internally and in user code, while reducing overall code size.

**Comment by MylesBorins** [comment]
@michaelobriena should we close this?
