### ISSUE TITLE
we should have some form of test harness

### ISSUE THREAD

**Issue by AdrianRossouw** [Famous/famous#224]
So this is probably subjective on some level, but I'm starting to get kind of nervous about not being able to conclusively prove certain issues are resolved.

We should use this issue for actually implementing things, so I've started a thread on the mailing list for us to discuss our options:

[testing: how do we confirm issues are fixed and detect regressions](https://groups.google.com/forum/#!topic/famous/Uzm2BuHhfM8)

**Comment by michaelobriena** [comment]
This is coming in the next release.
