### ISSUE TITLE
Scrollview outputFrom to provide additional parameters

### ISSUE THREAD

**Issue by StephanBijzitter** [Famous/famous#227]
I'm trying to lay out my surfaces in a grid within a scrollview but I am only provided with an offset parameter, which can only be used to calculate the index of a surface if the scrollview hasn't scrolled.

		var output = function(offset) {
			var index = Math.floor(offset / 250); //only correct if scrollview hasnt scrolled
			var column = index % 2;
			var row = Math.floor(index / 2);
			return Transform.translate(column * 200, row * 250 + offset % 250);
		};

Provided all surfaces within the sequence have a size of [200, 250] and the scrollview was initialised with a direction along the y-axis.

It would be much more useful if we could have the same arguments we get with SequentialLayout:
input, offset, index

**Comment by MylesBorins** [comment]
I'm going to close this for now.  I doubt that we are going to make api changes like this  Please feel free to re open if you like
