### ISSUE TITLE
mixing famous with a web app

### ISSUE THREAD

**Issue by dcsan** [Famous/famous#238]
I'd like a mixed mode app, that uses famo.us for some screens, but other areas using normal web  features like a native browser scrollview.

Currently famous seems to actively prevent you doing this see:
-  [Engine.js purposefully breaking touchmove](https://github.com/Famous/core/issues/14) from back in April
- [famous breaks normal webapp scrolling](https://github.com/Famous/views/issues/45)

there was a [commit](https://github.com/Famous/famous/commit/3ebbb56a36dea48ec2392ddc963a27c7717adf31) adding an appMode flag, but not sure if this is working? I tried this:

```
Engine = require('famous/core/Engine')
Engine.setOptions({appMode: false})
```

but famous still breaks the rest of any app.

I also tried to initialize famous using a within a specific div. this works, famous renders in that area, but scrolling is still broken. I think because of famous default css?
so next thing using a:

``` js
$("body").css("overflow")
"hidden"
$("body").css("overflow", "visible")
[
<body style=​"overflow:​ visible;​">​…​</body>​
]
$("body").css("overflow")
"visible"
```

confirm its changed, however, still no scroll. what else could be going on?

also tried [this hack](https://github.com/Famous/views/issues/45#issuecomment-49537008) but no scroll, at least on iOS simulator. not sure how blink responds to these edge cases either.

So, since this has been an issue since April, is it just not a priority to allow famous to coexist with other web technologies? I worry that might limit adoption beyond demos.

This scrollview debate is really the achilles heel of famous (hello hackernews!), I'm sure a huge amount of effort is going into creating famous' own scrollview that maybe one day could approach what we have already and working, but ... meantime it would be good to be able to mix and match!

**Comment by lugotm** [comment]
@dcsan I was able to mix famous with a web app. The only problem I have is destroying/removing Famous after clearing/removing the:

`<div id="famous-app" style="overflow:hidden;">`

tag from the DOM.

**Comment by jd-carroll** [comment]
Is this what you are looking for #600 ?
