### ISSUE TITLE
Low priority - Scrollview with mouse scroll wheels

### ISSUE THREAD

**Issue by StephanBijzitter** [Famous/famous#244]
Most mouse scroll wheels do not add velocity to the scrollview. They stop as soon as the wheel stops scrolling. To give all users a uniform experience, velocity should be added, as this is what all touch users (touch including mouse/track pads) get to enjoy.

The wheel currently makes scrolling look ugly and while it certainly has no priority whatsoever, it would be nice to add this later down the road.

**Comment by MylesBorins** [comment]
@michaelobriena should we close this for now awaiting a proper discussion in mixed mode?
