### ISSUE TITLE
Scrollview to respond to mouse scroll events even if direction does not match

### ISSUE THREAD

**Issue by StephanBijzitter** [Famous/famous#245]
Having a horizontal banner on my web application, scrolling can currently only be done by using a touch-enabled device, a touch/track pad or a Magic Mouse. My super-epic Mionix Naos 8200 has a scroll wheel that can only scroll through the y-axis.

An option should be added to horizontal scrollviews to process vertical scrolling from a mouse. Vertical scrolling would then result in horizontal movement.

**Comment by michaelobriena** [comment]
I cannot find it.

**Comment by michaelobriena** [comment]
This is definitely possible though.
