### ISSUE TITLE
GenericSync spitting out too many events

### ISSUE THREAD

**Issue by StephanBijzitter** [Famous/famous#252]
MenuButton.js: https://gist.github.com/StephanBijzitter/067cb23d2edb11585d65
Snippet for menu visibility: https://gist.github.com/StephanBijzitter/3cd05070ce21339800ef
Based on: http://famousco.de/2014/07/material-designish-button-animation/

Expected behaviour depends on the state of the app: the page it is on and whether the menu is open or closed.

To give consistency to this report I will define the following:
Press: any event that indicates either a touch start or mouse press event;
Release: any event that indicates either a touch end or mouse release event;
Hold: a period of 600 milliseconds or more between press and release.
Click: a period less than 600 milliseconds between press and release.

The button has two states:
0: Hamburger (menu) icon
1: Back arrow

When the state is 0 and the user clicks or holds the button, open the menu if it is closed or close the menu if it is open.
When the state is 1 and the user clicks the button, go back to the parent page of the current page.
When the state is 1 and the user holds the button, change state temporarily to 0 and show the menu.
*) The user then closes the menu by pressing or holding the button once again, reverting its icon back to 1 in the process.

On computers without touch screens, this works as expected. On some mobile phones, this works as expected. Sadly, not on all phones.

On a test Huawei, when clicking the icon with state 0, the menu shows and instead of staying visible, it hides itself. The same behaviour occurs when holding the icon with state 1. This leads me to believe that it receives multiple events. The first of these would cause the menu to open, and the second would cause it to close.

So I tested this theory and commented out the mouse sync from the generic sync and as I suspected, the Huawei had no more issues. I have also tested this on the iOS Simulator, which gave me the exact same behaviour.

It therefore seems that on some phones, both mouse and touch events are emitted from a generic sync if the user touches the screen.

**Comment by michaelobriena** [comment]
Closing as DesktopEmulation should solve this.  Will reopen if needed.
