### ISSUE TITLE
A Draggable() Surface blocks input focus

### ISSUE THREAD

**Issue by talves** [Famous/famous#260]
When a Draggable modifier is subscribing to a surface containing an input element, the input cannot aquire focus.

The surface can be dragged, but the input will not take focus.

**Here is the code and [jsfiddle](http://jsfiddle.net/mhnr5tn8/6/)**

```
    var Engine = require('famous/core/Engine');
    var Surface = require('famous/core/Surface');
    var Transform = require('famous/core/Transform');
    var Draggable = require('famous/modifiers/Draggable');

    var mainContext = Engine.createContext();

    var surface = new Surface({
        size: [300, 100]
    });

    var draggable = new Draggable();

    draggable.subscribe(surface);

    var content = '<input type="text" name="name" value="test">';
    surface.setContent(content);

    mainContext.add(draggable).add(surface);
```

This was brought up by @janober when done in famous-angular

**Comment by steveblue** [comment]
Seeing this same issue with any MouseSync. We had declared a MouseSync in a global scope to scroll some of our custom layouts where the Scrollview wasn't quite working. The MouseSync prevented all inputs from getting focus on click. We had to programmatically achieve focus on click for each input to have both the MouseSync and focus() work in the same layout. Not a deal breaker, but definitely caused a headache for one of our developers trying to diagnose the issue. It makes sense to me why the inputs were losing focus, but would like it if the input events could just bubble up.
