### ISSUE TITLE
Running the periodic table demo locally

### ISSUE THREAD

**Issue by zoomclub** [Famous/famous#272]
I see that there is a new online version of the periodic table demo but I'm not seeing a link to downloadable source. How do I run this demo for myself locally?

**Comment by Joel-Kornbluh** [comment]
+1 For open sourcing the periodic table demo.

**Comment by benag** [comment]
+1

**Comment by ricardogarcia** [comment]
+1

**Comment by miquael** [comment]
+11:11

yes, please.  i'd eat plutonium for an open demo ...

**Comment by MylesBorins** [comment]
this will not be happening on the current platform.  Closing for now
