### ISSUE TITLE
Infinite loop in core/ViewSequence for zero length array

### ISSUE THREAD

**Issue by bguiz** [Famous/famous#289]
These are the lines that are running hot:

- https://github.com/Famous/famous/blob/0f36180b0ac3432d12b7e12288f94986b4f9b39b/core/ViewSequence.js#L140
- Scrollview _normalizeState (closure)
- Scrollview.prototype.render

I am not familiar enough with the code base to submit a PR for this, but I think this is where the problem is.

The same error is avoided in another possible location:

- ViewSequence.Backing.prototype.reindex  appears to check when the array is empty (`if (!this.array[0]) return;`):
   - https://github.com/Famous/famous/blob/0f36180b0ac3432d12b7e12288f94986b4f9b39b/core/ViewSequence.js#L68

To reproduce: 

    var lines = [];
    var node = new ScrollContainer({
        scrollview: {
            direction: 1,
        },
    });
    node.sequenceFrom(lines);
    //then add node to the scene graph
    //infinite loop occurs upon first render of scene graph

**Comment by MylesBorins** [comment]
290 has landed
