### ISSUE TITLE
Transitionable pause/unpause

### ISSUE THREAD

**Issue by zoneblaze** [Famous/famous#295]
Is there anyway to pause/unpause a Transitionable? All I can see is the halt property which seems to kill the tween. The app I am currently building, users need to be able to pause/unpause animations at any stage, not sure how this can be best achieved with the famous framework?

**Comment by MylesBorins** [comment]
not going to be fixed here. Please take a look at the new transitionables in mixed mode

**Comment by zoneblaze** [comment]
Had a look, looking good, thank you.
