### ISSUE TITLE
v3-beta: Safari mobile viewport zooms out to include surface rendered outside of the view port

### ISSUE THREAD

**Issue by trobbertze** [Famous/famous#320]
The following code:

<pre><code>
require([
      'famous/core/Engine',
      'famous/core/Modifier',
      'famous/core/Surface'
    ], function(
        Engine,
        Modifier,
        Surface){

    var context = Engine.createContext();

    var surface = new Surface({
      size: [undefined, undefined],
      properties: {
        backgroundColor: 'red'
      }
    });

    context.add(new Modifier({
      align: [1, 1]
    })).add(surface);

});
</pre></code>

Renders the following in Safari Mobile:
![img_1775](https://cloud.githubusercontent.com/assets/2182401/4374777/c9cd3d9e-4336-11e4-8ec0-6c682470a7a4.PNG)

**Comment by MylesBorins** [comment]
closing for now.  Please re open if problems presist
