### ISSUE TITLE
Question about opacity: 0.999999

### ISSUE THREAD

**Issue by kof** [Famous/famous#323]
I did some research on that and found out that opacity < 1 on absolute/relative elements trigger stacking context (https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Understanding_z_index/The_stacking_context).

But also it seems like any transform value or transform-style: preserve-3d,  perspective and other things (http://stackoverflow.com/questions/16148007/which-css-properties-create-a-stacking-context) lead to a stacking context.

So if every surface has anyways a matrix3d as well as transform-style: preserve-3d; why is opacity < 1 still used?

**Comment by michaelobriena** [comment]
This now matters because of the Safari ios8 implementation.

**Comment by michaelobriena** [comment]
It will stop rendering things that are only partially occluded.
