### ISSUE TITLE
Poor scrollview performance on mobile

### ISSUE THREAD

**Issue by mellors** [Famous/famous#325]
As one of the goals of famo.us is to enable a perfomant scrolling, we are a little disappointed of the scroll perfomance in our prototype. On desktop browsers it's ok, but on mobile devices the perfomance is really bad.

Are there common and known pitfalls we should avoid? There are many images (which is not the case in the scroll examples) - is this a problem?

**Comment by MylesBorins** [comment]
closing for now. please feel free to reopen

**Comment by mutazmq** [comment]
I have created a ScrollView with 10 plain surfaces (no content in them) and scrolling is lagging. Scrolling velocity is choppy and not proportional to the touch velocity on my Android device, while it is great on my PC. Am I missing anything?
This is the code I'm using with Cordova. 

```
    var scrollview = new Scrollview();
    var views = [];
    scrollview.sequenceFrom(views);

    for(var i=0; i< 10; i++){
        var background = new Surface({
            content: '<h1>' + i + '</h1>',
            size: [undefined, 200],
            properties: {
                backgroundColor: 'blue'
            }
        });
        views.push(background);
        background.pipe(scrollview);
    }
    this.layout.content.add(scrollview);
```
