### ISSUE TITLE
SVG Element Compatibility

### ISSUE THREAD

**Issue by jackthe7th** [Famous/famous#330]
So I know Famo.us doesn't have a SVG Surface yet, and I kind of know how hard it would be to implement this, but maybe someday it could? The possibilities of being able to use an SVG element instead of as an image in Famo.us would be incredible. With being able to make an SVG with hierarchal layers in Illustrator and then import them into Famo.us with it's animation performance... Drool.

**Comment by etyp** [comment]
Any update on this? What would it take to implement a basic svg on a normal surface or maybe extend the Surface class?

**Comment by ivosabev** [comment]
+1

**Comment by max-degterev** [comment]
why why why this is the only thing that prevents me from using famous. I love built in physics, but I need SVG support too!

**Comment by michaelobriena** [comment]
@suprMax Development on this repository has stopped.  All work is being done over on https://github.com/Famous/engine.

Our DOMElement supports any tag type so you can create an SVG element if you would like.  If you would want more features to make it easier feel free to file an issue and we can take a look at how to implement the features you would need.

**Comment by max-degterev** [comment]
Yea I already decided to give it a try and see how it goes. I don't need very advanced SVG stuff at this stage. Thanks!
