### ISSUE TITLE
Lightbox docs are poor

### ISSUE THREAD

**Issue by totty90** [Famous/famous#347]
At https://famo.us/docs/views/Lightbox , setOptions(options) you have "Parameters: Options An object of configurable options for the Lightbox instance.". So which properties this object should have?

From the tutorial I can see:

    Lightbox.DEFAULT_OPTIONS = {
        // 'in' state
        inTransform: Transform.scale(0.001, 0.001, 0.001),
        inOpacity: 0,
        inOrigin: [0.5, 0.5],
    
        // 'show' state
        showTransform: Transform.identity,
        showOpacity: 1,
        showOrigin: [0.5, 0.5],
    
        // 'out' state
        outTransform: Transform.scale(0.001, 0.001, 0.001),
        outOpacity: 0,
        outOrigin: [0.5, 0.5],
        
        // transition parameters
        inTransition: true,
        outTransition: true,
        overlap: false
    };

Please add them to the docs.

**Comment by TheAlphaNerd** [comment]
This has landed in the new docs
