### ISSUE TITLE
v0.3.0 Scrollview size calculation not triggered

### ISSUE THREAD

**Issue by MajorBreakfast** [Famous/famous#369]
Ember can somehow update the views array in such a way that the size calculation of the scrollview isn't triggered. This isn't specifically an ember problem: No matter how the views array is updated the Scrollview should adapt to it accordingly. Somehow there's a small window in which changes don't get detected.

I created a [demo project](https://github.com/MajorBreakfast/famous-scrollview-problem) that illustrates the problem. `main.js` holds the source. I've kept it brief and also added some explanations as comments.

To quickly try it out, I've hosted it via github pages.

The [demo page](http://majorbreakfast.github.io/famous-scrollview-problem/) shows that the size recalculation isn't triggered although the 10 items that get added after one second clearly get rendered. The Scrollview still thinks its content has height 0. Consequently it is possible to scroll the bottom edge all the way to the top.

Workaround: Trigger size calculation by manually setting the dirty flag. The [adjusted demo](http://majorbreakfast.github.io/famous-scrollview-problem/workaround.html) shows that now scrolling the bottom edge all the way to the top isn't possible anymore. All because [this line](https://github.com/MajorBreakfast/famous-scrollview-problem/blob/master/main.js#L38) has been uncommented.

Occurs in: Chrome, Firefox, iOS Safari (probably everywhere)

**Comment by MylesBorins** [comment]
I'm going to close this for now as we are not taking feature requests. Please feel free to reopen though
