### ISSUE TITLE
GenericSync - 'end' event doesn't return correct velocity

### ISSUE THREAD

**Issue by dinopetrone** [Famous/famous#384]
in 0.3.0 the GenericSync will no longer return the correct velocity.  It returns the last known velocity during an update.  This is a false assumption given that someone could click, drag really fast, stop for a duration, then release at that stopped point.  the GenericSync does not take into account the drop in velocity during the paused period.  

fix:  check the time between the last update and end and reduce velocity based on that duration.

**Comment by MylesBorins** [comment]
Fixed!!!
