### ISSUE TITLE
Want to change surface size inside scroll container.

### ISSUE THREAD

**Issue by agaase** [Famous/famous#394]
I wanted to change the size of a surface when its clicked among multiple surfaces in a scroll container using the code below

    listView.on("clicked",function(mod){
                  mod.setSize( [this.options.width,this.options.height-this.options.headerHeight],{
                         duration: this.options.transition.duration
                   });
    }.bind(this));

listview is where surface is actually created and mod passed is the modifier for that particular surface. Although Iam able to decrease the height; but its not increasing the height for that particular surface even though the scroll container adjusts other surface to move down according to the new height.
Is this a bug or Iam doing something wrong?

**Comment by MylesBorins** [comment]
Closing for now. Please reopen if you have a test case
