### ISSUE TITLE
Using RenderController inOriginFrom[1,0] not working if I need to rotate surface from origin 1 towards left.

### ISSUE THREAD

**Issue by pranalisnapwork** [Famous/famous#395]
Using version 2.0 working fine but when switched to v 3.0 creates alignment and origin problem.
I want to animate different pages using render controller I am setting inOriginFrom[1,0] and outOriginFrom[0,0] as mentioned below-

var viewRendererMod= new Modifier({
origin:[0.5,0.5],
align:[0.5,0.5], 
size:[window.innerWidth-58,undefined], 
});
renderController = new RenderController({
inTransition: {curve: Easing.easeOut, duration: 1000},
outTransition: {curve: Easing.easeIn, duration: 1000},
overlap: true,
});
this.add(viewRendererMod).add(this.viewRenderer);
this.viewRenderer.add(renderController);
renderController.inTransformFrom(function(progress) {
return Transform.rotate(0,(-Math.PI/1.5)(1.0 - progress),0);
});
renderController.outTransformFrom(function(progress) {
return Transform.rotate(0,(Math.PI/1.5)(1.0 - progress),0);
});
renderController.inOriginFrom(function() { return [1,0]});
renderController.outOriginFrom(function() {return [0,0]});

The coming page should come from origin[1,0] and and should go out from origin[0,0] with rotation but this is not happening when switched to version 3.0 the incoming and outgoing animation is going from origin[0,0] or beyond that. Please suggest me a solution if possible.

**Comment by MylesBorins** [comment]
closing for now
