### ISSUE TITLE
cannot set TextareaSurface target's value to empty string

### ISSUE THREAD

**Issue by okhobb** [Famous/famous#414]
the deploy function is preventing this as is:

    /**
     * Place the document element this component manages into the document.
     *
     * @private
     * @method deploy
     * @param {Node} target document parent of this container
     */
    TextareaSurface.prototype.deploy = function deploy(target) {
        if (this._placeholder !== '') target.placeholder = this._placeholder;
        if (this._value !== '') target.value = this._value;
        if (this._name !== '') target.name = this._name;
        if (this._wrap !== '') target.wrap = this._wrap;
        if (this._cols !== '') target.cols = this._cols;
        if (this._rows !== '') target.rows = this._rows;
    };

InputSurface does not do the same check on this._value !== ''

**Comment by MylesBorins** [comment]
@michaelobriena should we execute on this?
