### ISSUE TITLE
Documentation does not clearly document events

### ISSUE THREAD

**Issue by garytaylor** [Famous/famous#425]
I am fairly new to famous (about 2 months) and I often find myself digging into the code to find things out because the documentation is not good enough.
The main thing is that events are not documented.

For example, I went to use the scrollview (I am using famous-angular - but this applies to just famous as well) and I could not find out what events to expect from it anywhere.  There was the occasional mention of an event in the text.

I am a heavy user of ExtJS which has the best documentation I have ever seen for a project.  This clearly documents things like this using the @event tag in the source code and it uses JSDuck to produce the documentation.  Famous could also very easily use JSDuck rather than YUIDoc, but I am sure that you could configure YUIDoc to do the same thing with events (and anything else that is not well documented).

If you need any help with docs, I would be glad to help as it would help me learn how things work as well.

Regards

Gary

**Comment by TheAlphaNerd** [comment]
Closing for now... feel free to reopen
