### ISSUE TITLE
Multiple click/touch events registered in iOS Safari Web App Mode

### ISSUE THREAD

**Issue by ROUND** [Famous/famous#427]
In Mobile Safari on.click handlers fire once, showing correct behavior: https://www.dropbox.com/s/l9mez2xvmc5zdqr/correct.mov

However, when made as a Web App (via Add to Home Screen) events seem to be firing twice in the same location, and hitting other surfaces: https://www.dropbox.com/s/qkg4bunuu9xjkv5/incorrect.mov

Here's a fiddle: http://jsfiddle.net/a30d637h/

The code for both of these is identical, but behavior is different. Perhaps something to do with FastClick or how iOS handles input differently in this mode?

**Comment by istvanskeri** [comment]
I'm experiencing a similar issue with the flipper. In my ios hybrid app i tap the flipper, it flips twice. Works fine on chrome/safari.  Can any of the core devs look at this issue please? This is a show stopper for anyone trying to deploy to ios apps

**Comment by nihilence** [comment]
Is there still interest in solving this within famo.us? If so, I modified the Flipper module for a project and it works as desired.

**Comment by pilwon** [comment]
@nihilence Great, please open a PR to share your fix with the community :+1:

**Comment by MylesBorins** [comment]
@nihilence saw the PR... thanks for submitting.  I'm not 100% it can land exactly as it is, but we can find a way to make it work!
