### ISSUE TITLE
GridView with scrolling without empty spaces between surfaces

### ISSUE THREAD

**Issue by extempl** [Famous/famous#440]
Hey guys.
I have had such a task as you see in the title with square surfaces.
I thought, that I only need the gridView, but this was a mistake, since it can't be normally scrolled (with caching). So I made my own scrollable gridView which based on the next layuot:
```
  scrollView
    containerSurface (size: [undefined, screen.width / cols])
      gridView (dimensions: [cols, 1])
        surface
```
And all seems to be ok, but appears the problem with empty spaces between surfaces: http://screencast.com/t/0ewtBsOt4VNY
Where you can see 6 cols and `320px` width. So in result surfaceSize is `53.333.. x 53.333..` which causes spaces problems. So I did following:

1. vertical spaces (between rows): 
`containerSurface (size: [undefined, Math.ceil(screen.width / cols)])`
So height is now equals to `54px` instead of `53.333` which causes `.5px` step for scrolling and spaces between rows.

2. horizontal spaces (in fact, in the end of row which equals modulo of `screen.width - Math.floor(screen.width / cols) * cols` which equals to `2px`). So I did the following:
I forgotten about gridView and started using SequentialView with calculating each surface size by following formula:
```javascript
sideSize = screen.width / cols
biggerSizeCount = screen.width % Math.floor(sideSize)
// ... row surfaces loop
  size = [Math[i < biggerSizeCount : 'ceil' ? 'floor'](sideSize), undefined]
```
So now I adding per pixel for first `(n)` surfaces, where `(n)` is a modulo (54, 54, 53, 53, 53, 53)
Which looks much and much better: http://screencast.com/t/NF432nxCS

So, anyone know, can it be done in any other ways? If no, I think such layout should be present in the famous.

**Comment by MylesBorins** [comment]
I am going to close this assuming we are not going to implement this.  Please feel free to re open or submit a PR
