### ISSUE TITLE
Repulsion stops working when Particles collide

### ISSUE THREAD

**Issue by PEM--** [Famous/famous#454]
When a `Repulsion` with negative `strength` is applied from one `Particle` A on a `Particule` B, the `Particle` B is attracted to the `Particle` A. Which is good.

But when the `Particle` B touches `Particle` A, the `Repulsion` is not applied anymore.

In this [reproduction scenario](http://codepen.io/PEM--/pen/aKsfl?editors=001), if you remove the initial velocity on `Particle` B (the satellite) (removal can be done by commenting line 49), it should end up crashing on the `Particle` A (the planet) with a spring motion.

**Comment by MylesBorins** [comment]
closing for now. Please feel free to re open
