### ISSUE TITLE
ScrollView and trackpad

### ISSUE THREAD

**Issue by richardscarrott** [Famous/famous#458]
I've experienced jank when flicking a ScrollView with the trackpad in Chrome on a MacBook Pro whereby the scroll stops abruptly.

I've noticed the problem is not present when preventing the ScrollView from windowing by setting `margin` to `Infinity`.

I initially thought it was caused by the extra layout operation required on each engine tick due to DOM elements being taken in and out of the browser's render tree however the timeline indicates each frame is well within budget.

I therefore think it might might be an issue with the wheel event when a new element is rendered by the browser.

**Comment by MylesBorins** [comment]
Closing for now, please feel free to re open
