### ISSUE TITLE
Perspective is not applied when StateModifiers are initialized with no initial Transform

### ISSUE THREAD

**Issue by PEM--** [Famous/famous#466]
I set up a the main context with an initial perspective. The render tree only contains one `StateModifier` with no initial `Transform` and one `Surface`. When the `Surface` receives a click event, I set up a `Transform` on the `StateModifier`. Nothing moves. The perspective is only applied if I **double click** on the `Surface`.

If I initialize the `StateModifier` with a `Transform`, the perspective is properly applied.

I've set up a [Pen for reproduction](http://codepen.io/PEM--/pen/NPKJyZ?editors=001).

Uncomment line 17 to circumvent the issue.

**Comment by MylesBorins** [comment]
Is this still happening?

**Comment by PEM--** [comment]
Still appearing. You can check out the Pen: [Pen for reproduction](http://codepen.io/PEM--/pen/NPKJyZ?editors=001).

**Comment by MylesBorins** [comment]
please try mixed mode
http://github.com/famous/engine

**Comment by PEM--** [comment]
Will do :wink: and thanks for the good stuff :+1:
