### ISSUE TITLE
Helper for testing browser support

### ISSUE THREAD

**Issue by jaandrews** [Famous/famous#470]
It would be helpful to have something to make it easy to test whether a browser can run famous, in order to create "browser not supported" messages.

Each module could have a list of required features that feed in to a master list of required features for all of the modules currently loaded into a particular famous instance..There would also need to be a helper to register additional tests, to handle cases where developers add features beyond vanilla famous.

The developer could then call something like "Utility.WorksInBrowser()" to check against that requirement list.

**Comment by dcworldwide** [comment]
+1. Famo.us should really state which browsers are supported on their product site.

**Comment by MylesBorins** [comment]
This will be better supported in our MixedMode release.

**Comment by MylesBorins** [comment]
please feel free to keep the conversation going
