### ISSUE TITLE
Text input fields shift offscreen on Android

### ISSUE THREAD

**Issue by LostMoho** [Famous/famous#471]
I'm having a problem with famo.us and the Chrome browser on Android. What I'm encountering is that if you have a text input field and you tap it to start typing, when the Android keyboard appears, the text field shifts offscreen and becomes invisible so that you can't really see what you're typing.

I've created a simple example here:

http://lostmarble.com/misc/MobileKeyboardBug/

There are two HTML files there - both work fine in a desktop browser and in mobile Safari. Both files use the same JavaScript, but one references famo.us 0.2 and the other famo.us 0.3. To see the bug, you'll need to visit these pages in Chrome on Android. (I'm using Chrome 38.0.2125.114 with Android 4.4.4.)

The version with famo.us 0.2 works fine:
http://lostmarble.com/misc/MobileKeyboardBug/index_0.2.html

The version that uses 0.3 has a problem. When you tap the input field, as the Android keyboard appears, the text field shifts upwards off the screen and becomes invisible to the user:
http://lostmarble.com/misc/MobileKeyboardBug/index_0.3.html

Besides the text input, I added a red square and a green square to show the corners of the screen. In the 0.3 version, you can see these squares fly away as the keyboard appears.

If anyone wants to explore these files locally, I've packaged them up here:
http://lostmarble.com/misc/MobileKeyboardBug/KeyboardBug.zip

I've done some experimenting and found that if you mix the 0.3 JavaScript with the 0.2 CSS, it may improve the situation. That's obviously not a proper solution, but it may be a hint about where things are going wrong.

**Comment by MylesBorins** [comment]
closing for now... if problem is persisting please re open
