### ISSUE TITLE
0.3 FlexibleLayout ratios transition broken

### ISSUE THREAD

**Issue by StephanBijzitter** [Famous/famous#474]
The transition for the ratios is broken as a result of the 0.3 release which does not handle arrays as arguments for a transitionable anymore. Thus, when the ratios change (and the transition is supposed to be made), errors occur.

**Comment by alexisohayon** [comment]
@speigg I would love an example of how you make it work. 
I'm currently learning how to implement famo.us into a large angular app, this could help me save hours :v:
