### ISSUE TITLE
famous-root not needed when createContext is called with specific elements.

### ISSUE THREAD

**Issue by trusktr** [Famous/famous#492]
I noticed that having the `famous-root` class on the `body` and `html` tags allows ScrollViews to work properly, but when the context isn't the `body` (i.e. I've called `Engine.createContext(someDiv)`) then the `famous-root` class shouldn't be added because it set overflow hidden, making it undesirable when you're writing a 'traditional' HTML app then putting a Famo.us context inside some element somewhere in the layout. It's possible to override the `overflow:hidden` setting, but this introduces an undesirable effect of breaking ScrollView (it won't scroll anymore), and some other things like changing the apparent z order of things.

Fixing issue #491 might be required in order to fix this issue.

**Comment by MylesBorins** [comment]
closing for now.
