### ISSUE TITLE
Using ViewSequence.splice after ViewSequence.unshift raises exception

### ISSUE THREAD

**Issue by IjzerenHein** [Famous/famous#496]
The following code causes an exception on the splice call:

```javascript
var viewSequence = new ViewSequence();
viewSequence.unshift(new Surface()); // insert 1 item
viewSequence.unshift(new Surface()); // insert 2 item
viewSequence.splice(1, 0, new Surface()); // insert item in between
```

Looking at the code it seems to be something with `_.firstIndex`. When you use unshift it sets that variable, and .splice uses, but it seems to result in an invalid array-index.
I don't understand how the code is intended, so I couldn't fix it myself.

**Comment by MylesBorins** [comment]
please try mixed mode
http://github.com/famous/engine
