### ISSUE TITLE
Scrollview pageChange event is inconsistent

### ISSUE THREAD

**Issue by whatisor** [Famous/famous#503]
Scrollview can emit pageChange event but it does not work stable (Sometime emit, sometime skip)

**Comment by leestar** [comment]
I can verify this. This issue is also occurring for me.

Any updates to this?

**Comment by TheAlphaNerd** [comment]
@wgester can you comment?

**Comment by leestar** [comment]
Are there at least any workarounds while waiting for a fix? Maybe some other event to listen to that is more reliable?

**Comment by leestar** [comment]
Can this be bumped??

**Comment by ivelfan** [comment]
I have the same problem with the default configuration.
When I add pagePeriod and pageSwitchSpeed options, "pageChange" event works fine.

A plan to fix it ?

**Comment by leestar** [comment]
@ivelfan  I added both options, and it still doesn't fire consistently. What were your specific settings?

Devs, there are a few bugs holding back launch of my app, but this one is one of the most critical ones. Any plans to fix soon?

**Comment by veke** [comment]
Confirmed. With paginated scrollview with fullscreen height surfaces and with default settings. Page change event fires only if you move the view a little bit after the change. (code from scrollview example.js)

```
define(function(require, exports, module) {
    var Engine     = require("famous/core/Engine");
    var Surface    = require("famous/core/Surface");
    var Scrollview = require("famous/views/Scrollview");

    var mainContext = Engine.createContext();

    var scrollview = new Scrollview({paginated: true});
    var surfaces = [];

    scrollview.sequenceFrom(surfaces);

    for (var i = 0, temp; i < 40; i++) {
        temp = new Surface({
             content: "Surface: " + (i + 1),
             properties: {
                 backgroundColor: "hsl(" + (i * 360 / 40) + ", 100%, 50%)",
                 lineHeight: "200px",
                 textAlign: "center"
             }
        });

        temp.pipe(scrollview);
        surfaces.push(temp);
    }

    scrollview.on('pageChange', function() {

        var currentPage = scrollview._node.index;

        console.log(currentPage);

    });

    mainContext.add(scrollview);
});
```

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this bug.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive an  spirit to the famous engine, which can be found at --> http://github.com/famous/engine
