### ISSUE TITLE
Scrollview issues, ideas, improvements, overhaul?

### ISSUE THREAD

**Issue by StephanBijzitter** [Famous/famous#506]
So I've used Scrollview a lot now (two apps, released for iOS and Android) and quite honestly... it's quite limiting and often irritating.

The first annoyance I had is that anything added to a Scrollview is not automatically piping to it. I'd expect this to be default behaviour and to be able to toggle it off by a parameter, in the case of (for example) letting the app (instead of the user) regulate the scrolling.

The next annoyance was with the layout limitations, as the Scrollview is essentially a 1-column table. If I want to lay out products in a grid-like view, I have to wrap each two products in a layout and push the layout as a row to the Scrollview... creating a LOT of unnecessary clutter in both the code and runtime operations. The output function can be overridden, but does not provide any useful information about the Scrollview to be able to lay out anything properly.

So that's the third issue... it's as good as stateless because barely any events are emitted and those that are emitted are not always emitted. Try to get the currently shown components in the Scrollview and you have to resort to voodoo mathematics with a bit of witchcraft to season it. A lot of information about the Scrollview and its state is abstracted away to the extend where managing content is extremely annoying.

Speaking of managing content, that's the next issue. When removing and adding items to a Scrollview, unexpected things happen. The size for one does not always update accordingly and sometimes when it does, it can also cause the Scrollview to freeze in an ethereal space. The scroll position is an even greater issue, as it has no clue of what's going on anymore somehow.

So essentially we have a view that hides components when they're not rendered to be more performant... but a lot of wrapping needs to be done to make it work with anything but a 1-dimensional list of views.

*Scrollview should contain the following functions:*
* setPosition(position, transition)
* getPosition() -> position

These two functions should handle ALL movement within the Scrollview. The position object will contain the following keys:
* `position.absolute` an array of [x, y] coordinates
* `position.percent` a number in the range of 0 to 100 where 0 is defined by the top (or left) edge being visible and 100 is defined by the bottom (or right) edge being visible. Thus, if the Scrollview cannot continue to scroll anymore, either 0 or 100 would be returned and anywhere in between any given calculated value is returned.
* `position.index`  a number of the first visible renderable.
* `position.indices` or `position.indexes` an array of numbers for all visible renderables.

This position object is updated through the `setPosition` function and *no-where else*. When processing user-input this has to be done through this function.

*Scrollview should emit events even when handling them:*
* `positionChange` when the position object is changed (and thus setPosition) is called. This should be emit EVERY time, whether it's by user-input or programmed behaviour. When this event is emit, *at least* one of the following events HAS TO BE emit as well:
* `percentChange` when the position object's percent value is changed.
* `indexChange` when the position object's index value is changed.
* `indicesChange` or `indexesChange when the position object's indices or indexes value is changed.

*When the renderable sequence is modified, the position object must be updated:*
* Since the height (or width) of the Scrollview is now different, so will the position be.
* A `sizeChange` event should be emit to notify the programmer of the change. This event should contain at least the keys to describe the following values: The previous amount of renderables, the current (new) amount of renderables, the previous size of the renderables, the current (new size) of the renderables, the previous position and the current (new) position.

*To provide layout functionality, Scrollview must adopt SequentialLayout's behaviour:*
The output function should be provided with the following parameters:
* `previous` The previous renderable's boundaries (x, y, width, height), or (0, 0, 0, 0) if there is no previous renderable.
* `index` The current renderable's index.
* `viewport` The width and height of the Scrollview's visible viewport as an array.

The return value should be an array of the current renderable's boundaries.

There's probably a lot I am forgetting here, but I guess it's a start.

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this bug.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive an  spirit to the famous engine, which can be found at --> http://github.com/famous/engine
