### ISSUE TITLE
Draggable: provide configurable handleMovement implementation

### ISSUE THREAD

**Issue by g00fy-** [Famous/famous#510]
Default implementation should be moved to defaults. Some parts could be extracted, so the default implementation would be a composition of `boundingBox` and `snapToGrid` utils. 

Additional event `move` could be fired after running the implementation, in order to inform the data layer about the movement. AFAIK `eventOutput` / `EventHandler` is configurable (dispatching events can be asynchronous) therefore It may be not a good idea to cancel the movement if `event.preventDefault` was called.

This change would allow unlimited movement control (not only rectangular bounding box), for example:

-  dragging a surface only on top of other moving/animated surface 
-  custom snapping
-  perspective (Issue #68) 
-  other, unlimited control

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this bug.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive an  spirit to the famous engine, which can be found at --> http://github.com/famous/engine
