### ISSUE TITLE
Reactive streams

### ISSUE THREAD

**Issue by kof** [Famous/famous#516]
Have you ever thought to use this pattern for events handling, piping, mapping etc? I think it goes very much into the same direction you have right now with events but will make things way better.

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this bug.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive an  spirit to the famous engine, which can be found at --> http://github.com/famous/engine
