### ISSUE TITLE
RenderController Cleanup

### ISSUE THREAD

**Issue by aintnorest** [Famous/famous#524]
I've noticed that when using the RenderController to show and hide content my heap stack jumps in size not a lot but enough that it's concerning. Even the following extremely basic code slowly increases the stack size. With the content being so small you have to spam the button between snap shots but it still shows.

```js
var Engine = require('famous/core/Engine');
var Surface = require('famous/core/Surface');
var RenderController = require('famous/views/RenderController');
var StateModifier = require('famous/modifiers/StateModifiers');
var mainContext = Engine.createContext();
var ren = new RenderController();

function t1(){
  var temp = new Surface({size:[undefined,undefined],content:'hi',properties:{background:'yellow'}});
  return temp;
}
function t2(){
    var temp2 = new Surface({size:[undefined,undefined],content:'I am the second page',properties:{ background:'blue'}});
    return temp2;
}
mainContext.add(ren);
	var btn = new Surface({
		size:[100,40],
		content:'switch',
		properties:{
			background:'grey'
		}
	});
	btn.mod = new StateModifier({
		transform: Transform.translate(50,50,3)
	});
	mainContext.add(btn.mod).add(btn);

	var flipped = true;
	btn.on('click',function(){
		if(flipped){
			ren.show(t1());
			flipped = false;
		} else {
			ren.show(t2());
			flipped = true
		}
	});
```

I'll try and get something up on a fiddle that has more content without adding anything that wouldn't get gc'ed to show the problem without having to spam the show hide.

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this bug.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive an  spirit to the famous engine, which can be found at --> http://github.com/famous/engine
