### ISSUE TITLE
Make 3D States First-Class Citizens

### ISSUE THREAD

**Issue by jd-carroll** [Famous/famous#529]
I've been reading through the recent discussions on TT (#500) and I know there were some comments about completely deprecating StateModifier, but...

Moving forward, 3D state should be the default in all modifiers, case in point: (From StateModifier)
```
this._originState = new Transitionable([0, 0]);
this._alignState = new Transitionable([0, 0]);
```
I can imagine a situation where it would get a little out of hand trying to manage all of the 'default' 2D states.  Instead, the StateModifier should have something like:
```
this._originState = new Transitionable([0, 0, 0]);
this._alignState = new Transitionable([0, 0, 0]);
```
Then the StateModifier could be smart enough to handle different inputs.

JD

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive an  spirit to the famous engine, which can be found at --> http://github.com/famous/engine
