### ISSUE TITLE
0.3.2 TextArea setValue not working

### ISSUE THREAD

**Issue by SpaceJoe** [Famous/famous#531]
I guess this:

```js
TextareaSurface.prototype.setValue = function setValue(str) {
    this._value = str;
```

should be:

```js
TextareaSurface.prototype.setValue = function setValue(str) {
    if (this._currentTarget) {
        this._currentTarget.value = str;
    }
     else {
        this._value = str;
    }
```

**Comment by sebringj** [comment]
This bug is persisting for me in 0.3.5 when I do textArea.setValue('')    I just reference the _element instead and do _element.value = '' which is a no-no but right now its a no-go without that. 2014 huh? Its 2015 now FYI.
