### ISSUE TITLE
Calculating the absolute position of a surface

### ISSUE THREAD

**Issue by speigg** [Famous/famous#532]
In the [render-tree](https://github.com/Famous/famous/blob/master/guides/render-tree.md) guide, the following is stated: "In fact, if you want to know what the position, or opacity of a surface at the bottom of the Render Tree, you __*just*__ [emphasis mine] have to multiply the opacities and transforms of the Modifiers above it."

Has anyone figured out how to do this in practice?

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive an  spirit to the famous engine, which can be found at --> http://github.com/famous/engine
