### ISSUE TITLE
Scrollview goToPage(0) not working

### ISSUE THREAD

**Issue by speigg** [Famous/famous#537]
To clarify, `goToPage(0)` scrolls to the second item (index 1) when `goToPage(0)` is called in response to user input. If I call `goToPage(0)` without any user input, the scrollview correctly scrolls to index 0. If I call `goToPage(0)` in response to user input (such as the `click` event) on any surface that is also being piped to the Scrollview, then the scrollview incorrectly settles at index 1 instead of index 0. If I call `goToPage(0)` in response to user input on a surface that is NOT being piped to the scrollview, then the scrollview correctly settles at index 0.

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive an  spirit to the famous engine, which can be found at --> http://github.com/famous/engine
