### ISSUE TITLE
Last item in scrollview not getting removed.  Chrome & Opera Only.

### ISSUE THREAD

**Issue by The1nternet** [Famous/famous#542]
My project has a scrollview, and i can remove all items from this scrollview, except the last one.  The item gets removed from the DOM, but it is still being displayed.  This only happens for the last item.  Other items can be removed from the scrollview without issue.  I have tried re-creating this issue in a JSBin or something but it only seems to happen in my project.  
My project is located here:  https://github.com/The1nternet/Famous-Knockout-Example
The file that contains the problem is here:  https://github.com/The1nternet/Famous-Knockout-Example/blob/master/src/widgets/textArea/textAreaWidget.js

**To reproduce this issue:**
1. Run the project with: gulp watch 
2. Click the "patient history" item 
3. select an item from the drop down on the right and click "add".  This will make the item appear in the scrollview below the dropdown.  Add at least two items.
4. Click on one of the items that appeared, and it will be deleted, until there is only one item left.  Notice when you click the last item, this item gets removed from the DOM, but it is still being displayed.  If you scroll, or resize the browser, the display updates and the item disappears.  This only happens in Chrome.

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive an  spirit to the famous engine, which can be found at --> http://github.com/famous/engine
