### ISSUE TITLE
npm package is broke

### ISSUE THREAD

**Issue by markuz-brasil** [Famous/famous#543]
This days is pretty common to use browserify (or webpack) as a way of bundling frontend apps, and as such one is expected to `npm install famous` and later `var famous = require('famous')` to work. But it doesn't.

**Comment by TheAlphaNerd** [comment]
Hey markuz-brasil,

Wanted to quickly revisit this thread.  I have just finished completely rewriting the dist builder, so things finally work as expected again.  Further I want you to know that version of Famo.us published to npm will be in the commonJS pattern from now on

**Comment by markuz-brasil** [comment]
Awesome. For browserify folks that will be great.
