### ISSUE TITLE
famous carousel was released sept 5th? or not?

### ISSUE THREAD

**Issue by dcsan** [Famous/famous#548]
there was a carousel demo'd a way back in august, and promised for September 5th delivery
https://www.youtube.com/watch?v=97BDJUIysGw

> "we're gonna be releasing a carousel on september 5th, I guess we're locked to that date now"   
> @larryrobinson

where do i find it? I [looked in the various git repos](https://github.com/Famous?query=carousel)
or could it possibly be that famous didn't follow through after a fluffy demo for a press conference?

cc @nigelpegg @timjchin 

PS this is more of a forum or mailing list question but there doesn't seem to be any such [**active**](https://groups.google.com/forum/#!forum/famous) place for famous discussion other than GH issues?

**Comment by TheAlphaNerd** [comment]
I am closing this for now.  Expect more information about our widgets in the near future

**Comment by dcsan** [comment]
"near future" in famo.us speak is a bit of an abstract concept. by sept 5th next year seems possible?
