### ISSUE TITLE
scrollview / onPageChanged event

### ISSUE THREAD

**Issue by dcsan** [Famous/famous#549]
seems the scrollview is missing a few basic methods that most such widgets have, such as pageChanged. I do see some code in there inside a _private method:

https://github.com/Famous/famous/blob/master/src/views/Scrollview.js#L386

```js
  function _normalizeState() {
     ...
     this._eventOutput.emit('pageChange', {direction: -1, index: this._cachedIndex});
```

in order to catch this event would I use a sync or an eventHandler.subscribe on the scrollview itself?

I'm assuming when the carousel is released it will have this type of functionality, or the scrollview will have been brought up to par, but that was promised for september so who knows when it will materialize. 
meantime depending on undocumented _private methods is the recommended (only) way to get at this type of event? a pageChange seems like something most scrollviews would include in a 1.0

**Comment by TheAlphaNerd** [comment]
closing for now.  please feel free to reopen.

**Comment by dcsan** [comment]
> getCurrentIndex() does not always return the same index as reported in the pageChange event. This doesn't make much sense to me, and I think it's a bug in how the scrollview keeps track of it's current index.

yes i think i encountered this before, so probably best to leave this open?

**Comment by amcc** [comment]
i'm seeing the same issue with `getCurrentIndex()`. Often an incorrect value is given if i slowly scroll to the next page.

    scrollview.on('pageChange', function(event) {
                            // this sometimes gives the incorrect value
                            console.log('getCurrentIndex = ' + scrollview.getCurrentIndex());
                            // this is always correct
                            console.log(event['index']);
                        });

Another big problem with  `getCurrentIndex()` is that it gives a value of zero for the first two pages and every subsequent page is one less than it should be. This is when used on 'pageChange' in the code above, whereas the `event['index']` above is always correct. Oddly the code below gives the correct value for `getCurrentIndex()` though it still suffers from the same glitchy behaviour, often giving the wrong value:

    scrollview.sync.on('end', function(event) {
            console.log('getCurrentIndex = ' + scrollview.getCurrentIndex());
    });

**Comment by dcsan** [comment]
the problems you mention above have been around since the first public release.
