### ISSUE TITLE
Docs at famo.us/docs aren't as complete as those made by famous-doc-generator

### ISSUE THREAD

**Issue by lostfictions** [Famous/famous#552]
It seems a bit silly that, say, the only documentation on the website for the [Lightbox view](http://famo.us/docs/views/Lightbox) constructor reads:

    Lightbox(options)

    Parameters

    options (optional) Options An object of configurable options.

An object of configurable options! Okay! I'm not going to tell you what they are, though.

The generated docs fare a lot better in this respect, though they still don't document (for instance) default values for parameters. And even though I took the time to look up how to generate them, I wouldn't assume the average user would do the same -- especially when (ostensibly) the same stuff is available to instantly view online.

I know it seems minor and I don't mean to gripe or anything, but this sort of stuff strikes me as pretty important if you don't want to limit adoption of your framework to people willing to dig around in your source code?

**Comment by TheAlphaNerd** [comment]
This has been updated
