### ISSUE TITLE
famous/src/surfaces/ImageSurface.js suspected typo-bug

### ISSUE THREAD

**Issue by quentinburley** [Famous/famous#553]
famous/src/surfaces/ImageSurface.js: lines 48-54

origional version:
---
ImageSurface.getCache = function getCache() {
        return {
            urlCache: urlCache,
            countCache: countCache,
            nodeCache: countCache
        };
    };
---

Look carefully, I suspect it should be like this:
---
ImageSurface.getCache = function getCache() {
        return {
            urlCache: urlCache,
            countCache: countCache,
            nodeCache: nodeCache // *******
        };
    };
---

p.s. has anyone ever actually used ImageSurface.getCache() ?

**Comment by michaelobriena** [comment]
Great call.  Thanks @quentinburley

**Comment by michaelobriena** [comment]
Will be merged in 0.3.5 release.

**Comment by TheAlphaNerd** [comment]
fixed by 0057eaa
