### ISSUE TITLE
DesktopEmulationMode not suitable for devices with touch and mouse inputs

### ISSUE THREAD

**Issue by okhobb** [Famous/famous#554]
related to https://github.com/Famous/famous-angular/issues/222

in vanilla famo.us this is not an issue since users can choose not to include this module.

in famo.us/angular (i believe) users must use global (i.e. all modules are evaluated). there's no way out since the breakage results as a side-effect of including the module.

**Comment by alexanderGugel** [comment]
#555 and #558 would solve this by exposing an enable and disable method. For the time being, requiring a DesktopEmulationMode and FastClick is not side-effect free. This would require a breaking API change.

**Comment by TheAlphaNerd** [comment]
Thanks @alexanderGugel for getting those PR's in!

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive an  spirit to the famous engine, which can be found at --> http://github.com/famous/engine
