### ISSUE TITLE
Famousify in package.json?

### ISSUE THREAD

**Issue by trusktr** [Famous/famous#556]
Hi @TheAlphaNerd, would putting famousify in package.json's browserify.transforms property make sense? I saw it in the browserify-seed, but would it also work here?

**Comment by TheAlphaNerd** [comment]
Nope. We never require famous from within the framework, it is all relative
pathing.

Unfortunately there is no way to hijack require statements in parents
AFAIK. If we could do that then famousify would not need to exist in the
seed

Tldr nope

**Comment by trusktr** [comment]
@TheAlphaNerd Oh ok, I see. Yeah, it'd be nice if a package could specify which browserify transforms it needs. I'm in the scenario that I've made a package that depends on famous, then I have a project that depends on the package, but not directly on famous, so browserify was erroring out requiring f.e. `'famous/core/Surface'`. Adding famousify to the project doesn't seem to help, but adding famousify to the package that directly depends on famous makes it all work. I guess this good enough!

**Comment by TheAlphaNerd** [comment]
If you have famousify in the package json of your intermediary project you
should not get any errors.

Share me a link and I'll take a peak when I'm by my computer

**Comment by trusktr** [comment]
@TheAlphaNerd Yeah, it worked in the intermediary project. :) I made a new issue at https://github.com/substack/node-browserify/issues/1050 to suggest the idea of the child package being able to specify it's transforms.

**Comment by alexanderGugel** [comment]
Quoting [feross](https://github.com/substack/node-browserify/issues/1050#issuecomment-68616780):

> If you want their weird require magic (which automatically adds src/ for you) to work in your own module, then you need to add their famousify transform to your own module.

> They should just axe their src/ folder and move everything to the top level and get rid of that silly transform entirely. Why do people love to make simple things complicated?

What's the advantage of putting everything into `/src`?

**Comment by trusktr** [comment]
@alexanderGugel quoting @TheAlphaNerd 

> The src folder in famous is not going anywhere for the time being, it was necessary as the main folder was becoming very crowded and it wasn't clear which folders were source code versus support material.

I like that. It reduces clutter.

**Comment by trusktr** [comment]
@TheAlphaNerd What about having famousify move contents out of src into to the root of the famous package folder? Could that work?

**Comment by TheAlphaNerd** [comment]
Again nope. Browserify transforms work when the code is required in. Not as
a batch.

**Comment by trusktr** [comment]
@TheAlphaNerd Idea: it would be possible to add a `postinstall` script to package.json `scripts` that moves the files into the root, then famousify wouldn't be needed at all.

**Comment by trusktr** [comment]
Wait, postinstall would also mess things up during development. hmm.

**Comment by trusktr** [comment]
Or not! We develop from github, not npmjs. So perhaps a postinstall script would actually work.

**Comment by TheAlphaNerd** [comment]
There was a previous thread about a similar topic, I can dig it up later to
share (I'm in the car at the moment)

The short answer is no. We want to have code in dev the same as code in
production.

If we relied on pre publish magic for this we would be in a weird place if
you needed to run off the head.

If you have famousify included in the transforms section of your
intermediary project things should just work in the top level repo

**Comment by trusktr** [comment]
@TheAlphaNerd Why does the file structure need to be the same in dev as in prod? In production everything will be minified and bundled into a single file right? I can live with having to add famousify to a project just to make it compatible with browserify, but I'd prefer not to if it was possible. Hmmm...

**Comment by TheAlphaNerd** [comment]
Prod as in what is published to npm.

**Comment by alexanderGugel** [comment]
Wouldn't `var famous = require('famous'); var Engine = famous.core.Engine;` instead of `require('famous/core/Engine')` solve most of these problems (just like in the global-seed)?

**Comment by trusktr** [comment]
@alexanderGugel The thing with that is that then the whole library is required, but with package managers like webpack, browserify, and jspm, you can build a bundle that only includes the classes you actually use, so the file is as small as possible when it reaches the browser.

**Comment by TheAlphaNerd** [comment]
Indeed... Although you don't necessarily want to load the entire framework
in build.

**Comment by TheAlphaNerd** [comment]
You should in theory be able to do dead code elimination the get rid of
stuff... But it isn't guaranteed.

This actually becomes a bigger issue regarding what the canonical way to
use the framework is.

You could also make the required famous a glorified module loader itself.
Can't give code example right now because I'm on a phone.

Simply put, a larger syntax change like this is not trivial, and requires
changing documentation and education materials.

That is not a reason to not do it, but rather make sure it is definitely
the change we want

**Comment by trusktr** [comment]
Simply putting everything in the root for production and keeping require calls the same sounds easier.

**Comment by TheAlphaNerd** [comment]
There is a bunch of complexity this creates.

I'm not going to be able to reply to this anymore for now... Going for
dinner.

**Comment by trusktr** [comment]
Have fun! :)

*/#!/*JoePea
