### ISSUE TITLE
famo.us license

### ISSUE THREAD

**Issue by der-ede** [Famous/famous#562]
Hi there,

since I am not a lawyer, I was just wondering whether the license (MPL) famo.us runs under allows me to take the code of your famo.us university examples, change it, build my application around it and sell it commercially, use it as a boilerplate app so to speak?

Regards

**Comment by michaelobriena** [comment]
Hi @der-ede,

I am not a lawyer either and cannot give you legal advice but here are some useful resources.

https://www.mozilla.org/MPL/2.0/

https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2)

The examples fall in a weird spot so feel free to ping me at mike@famo.us and I can give you some better answers after talking with our lawyer.

**Comment by StephanBijzitter** [comment]
With the (lack of) complexity of the examples, you're probably going to completely overhaul them for your finished product, and thus you could say you fully created your product. In which case, as the MPL 2.0 states, you're allowed to sell your application.

The only thing you (in this specific case) should watch out for is that copyright infringement is still a thing, if you sell the tutorials then that's a big no-no, but selling software based on the tutorials (like a boilerplate) would be a-okay.

Please do note that I am not affiliated with Famo.us, though.

**Comment by TheAlphaNerd** [comment]
Closing for now.  Please feel free to reopen if you have more questions
