### ISSUE TITLE
Famo.us, v11.18.0 on npmjs.org.

### ISSUE THREAD

**Issue by trusktr** [Famous/famous#566]
@TheAlphaNerd Do you know famous@11.18.0 exists on npmjs.org? `npm install famous@11.18.0` lol

**Comment by trusktr** [comment]
The title of the public/index.html file is `OPA!`. xD

**Comment by TheAlphaNerd** [comment]
This was published prior to getting the name. No way to unpublish

**Comment by trusktr** [comment]
@TheAlphaNerd Have you tried `npm unpublish famous@11.18.0`? It didn't work?

**Comment by TheAlphaNerd** [comment]
Hmm
that did work.  My bad!

**Comment by trusktr** [comment]
Sweet, all seems well. jspm is installing 0.3.4 now.
