### ISSUE TITLE
Scrolling inside surface or dynamic Scrollview item

### ISSUE THREAD

**Issue by marcvdm** [Famous/famous#57]
It would be nice to either have a surface that can scroll its contents just like a scrollview does, or have a surface inside a scrollview that can have a height of true (`[undefined,true]`) and the Scrollview will still work when the content size changes

Currently i have a listener on the window resize to adjust to scrollview and its surface by calculating the contents height.
And when the size of the content changes, due to for example an accordion or dynamically appended content, i trigger a resize event onto the scrollview.

**Comment by jacksenechal** [comment]
@TheAlphaNerd can you elaborate on the fix that you referenced for scrollview? I don't see the overflow: scroll fix suggested above in the 0.3.x code so I assume it's got to do with true sizing on surfaces in scrollview or some such thing?
