### ISSUE TITLE
{appMode: false} + Transform.behind + Mobile Safari = invisible/missing surface

### ISSUE THREAD

**Issue by mhwheeler** [Famous/famous#575]
Engine.setOptions({appMode: false}) + StateModifier Transform.behind + mobile Safari causes the surfaces added to the state modifier to not appear. If you take away any one of these three conditions it works

I've created the following minimal reproduction example:
page: (view on mobile safari on iOS or iOS simulator then compare to normal browser)
http://mhwheeler.github.io/famous-demo/pages/Transform-behind.html
source:
https://github.com/mhwheeler/famous-demo/blob/gh-pages/src/Transform-behind.js

edit: reproduced using famous/0.3.4

**Comment by wheeler** [comment]
Still repro in 0.3.5 (repro example updated)

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive an  spirit to the famous engine, which can be found at --> http://github.com/famous/engine
