### ISSUE TITLE
No way to scroll text on iOS

### ISSUE THREAD

**Issue by bmatto** [Famous/famous#577]
There does not seem to be a way in which to have a surface that contains text which is scrollable.  I was pointed to this example http://jsbin.com/zopope/1/edit?js,output - but it fails on iOS.

I may be over thinking this, is there some way to allow scrolling on a particular surface / div on iOS?  Be it native, or in a scroll container?

**Comment by IjzerenHein** [comment]
I'm inclined to say, create a surface with size: [undefined, true] and add it to a ScrollView. This way you will be able to scroll the text vertically

**Comment by bmatto** [comment]
I was deving with 0.3.2 - updating to 0.3.4 solved my issue here.
