### ISSUE TITLE
Mouse/Touch events, AppMode and other confusing things

### ISSUE THREAD

**Issue by StephanBijzitter** [Famous/famous#579]
So I wanted to a release an app and on my desktop it worked fine, but on mobile it was a bit glitchy. (Android 4.4 with cordova 4.0). Turns out that `mousedown` is correctly fired on both devices, but `mouseup` is only fired on the desktop. I cannot rely on `click` because the duration of holding the mouse/finger determines what action will be executed. So then I thought about AppMode, but it is completely undocumented, what does it do?

**Comment by alexanderGugel** [comment]
When enabled, appMode prevents scrolling via browser by killing all `touchmove` events:

```javascript
    function initialize() {
        // prevent scrolling via browser
        window.addEventListener('touchmove', function(event) {
            event.preventDefault();
        }, true);

        addRootClasses();
    }
```

[Source](https://github.com/Famous/famous/blob/master/src/core/Engine.js#L137)

appMode is set to true [by default](https://github.com/Famous/famous/blob/master/src/core/Engine.js#L54).

To set the appMode option, `Engine.setOptions({ appMode: {Boolean} })` can be used.

**Comment by shupac** [comment]
How long has AppMode been an option in Engine and what's the benefit?

**Comment by StephanBijzitter** [comment]
yeah and how do i make sure that I don't get both mouse and touch events when input is received?

**Comment by aintnorest** [comment]
Chrome emulator is annoying it will fire both touch and mouse events when using it's touch emulation. At first I tried in conjunction with a touch library I was working with:
```
function typeControl(callback){
        var timer = 0;
        var timerON = false;
        var typeOFdata;
        var Callback = callback;
        //
        var timerCheck = function(tod){
            if(timerON){
                var time = timer - Date.now();
                if(time > 2500) typeOFdata = tod;
            } else {
                timerON = true;
                typeOFdata = tod
            }
            timer = Date.now();
        };
        var passThrough = function(type,data){
            timerCheck(type);
            if(timerON && typeOFdata === type) Callback(data);
        };
        var typeChecker = function(data){
            ('touch' in data)? passThrough('touch',data) : passThrough('mouse',data);
        };
        //
        return function(data){
            typeChecker(data);
        };
```
It basically just checks whats been fired recently and only lets that type through. I didn't like that and was also building an app with a lot of tables that needed click events. So I created a delegation library that made it so that I didn't need to worry about adding all those event listeners or removing them. I listen for:
```
		document.addEventListener('touchstart',eventSystem('pointerdown'));
		document.addEventListener('mousedown',eventSystem('pointerdown'));
		document.addEventListener('touchend',eventSystem('pointerup'));
		document.addEventListener('mouseup',eventSystem('pointerup'));
		document.addEventListener('touchcancel',eventSystem('pointercancel'));
```
If it finds the event on the element or any of it's parents it passes it the event then calls:
```
         event.stopPropagation();
 	 event.preventDefault();
```
Seems to stop a second event of the other type.

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive an  spirit to the famous engine, which can be found at --> http://github.com/famous/engine
