### ISSUE TITLE
Body.js: setting angularVelocity is non-functional

### ISSUE THREAD

**Issue by aldenderfer** [Famous/famous#580]
Setting a physics Body's `angularVelocity` property at creation (or using its `.setAngularVelocity` method) has no effect, because nowhere in the codebase is it used to calculate angular momentum. As a consequence, when this method

```
Body.prototype.updateAngularVelocity = function updateAngularVelocity() {
    this.angularVelocity.set(this.inverseInertia.vectorMultiply(this.angularMomentum));
};
```

 is called from Body's `._integrate` method, it effectively overrides (using `angularMomentum`) whatever the angular velocity was set to manually.

**Comment by michaelobriena** [comment]
@browles

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive an  spirit to the famous engine, which can be found at --> http://github.com/famous/engine
