### ISSUE TITLE
Not able to move website created in Famous on iOS device

### ISSUE THREAD

**Issue by pbrazdil** [Famous/famous#581]
I have a problem with website what I've created in famous. 

When I try to open it in safari / chrome on iPhone it's working great but there is one problem. Using my finger I can't move page at all. Therefore if browser's toolbar is hidden I can't even open it and I need to kill browser and run him again.

This is happening also in official examples. For example [examples/views/Scrollview/example.html](https://github.com/Famous/famous/blob/master/examples/views/Scrollview/example.html). Can't move the page, on the first sight it seems like everything is frozen but in reality everything work, just website does not respond to any touch event.

What I am suppose to do to fix this? Why is this even happening?

**Comment by pbrazdil** [comment]
anyone please?

**Comment by michaelobriena** [comment]
We surpress window touchmove events.

**Comment by michaelobriena** [comment]
https://github.com/Famous/famous/blob/develop/src/core/Engine.js#L137

**Comment by michaelobriena** [comment]
If you get rid of that you should be good.

**Comment by MylesBorins** [comment]
closing.  Please re open if you need to
