### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by MarcGodard** [Famous/famous#583]
I know this isn't the right place for this, but the site kinda sucks at explaining stuff, and couldn't really think of a better place to ask. I am also 100% new to famo.us and 80% with requireJS. I am pretty sure this is a stupid requireJS question... but again where to ask when learning 100% on your own.

I have this...

```javascript
require.config({
    paths: {
        ...
        famous: '../libs/famous/dist/famous'
    }
});
```

which works with ALL my other libraries that I use.

then I want to use famo.us in a module so I do this... but wait... requireJS is missing stuff??? lol

```javascript
define(['app', '...', 'famous'], function(app, ..., famous) {

    var Engine = require('famous/core/Engine');
    var Surface = require('famous/core/Surface');

    var mainContext = Engine.createContext();

    var firstSurface = new Surface({
      content: "<h3>Hi!</h3><p>...</p>",
      size: [200, 200],
      properties: {
        backgroundColor: 'rgb(240, 238, 233)',
        textAlign: 'center',
        padding: '5px',
        border: '2px solid rgb(210, 208, 203)',
        marginTop: '50px',
        marginLeft: '50px'
      }
    });

    mainContext.add(firstSurface);
});
```
It looks like the famous/core/Surface is to use the source files... but I want to use the famous.js file only because I don't want to over complicate anything.

I must really recommend better documentation or an example using the requirejs stuff that doesn't assume you have the source files. (Yes I looked at the requireJS seed and it was the same, also looked at the examples in the starter kit)

I also have another basic question that I couldn't find an answer to... Can you mix famo.us with html? I mean what if I just wanted one div animated?

**Comment by TheAlphaNerd** [comment]
Hey Marc,

Check this out —> https://github.com/Famous/requirejs-seed

Basically all you want to do is patch famous to ```../libs/famous/src``` and everything will work :D

**Comment by TheAlphaNerd** [comment]
Also for what it is worth... sourcing via path and the dist should still work absolutely fine!  You can use Famous as a global object with dot notation (if you add the dist script and then just call to famous), although our docs for the most point do not use that syntax.
