### ISSUE TITLE
Scale Transform in ModifierChain results in a side-effect of translation

### ISSUE THREAD

**Issue by neeharik** [Famous/famous#587]
Changing Scale in ModifierChain results in translation of the surface.

Code to demo the behavior.

define(function(require, exports, module) {
    var Engine        = require('famous/core/Engine');
    var Modifier      = require('famous/core/Modifier');
    var Surface       = require('famous/core/Surface');
    var Transform     = require('famous/core/Transform');
    var ModifierChain = require('famous/modifiers/ModifierChain');
   
    var mainContext = Engine.createContext();

    var modifierChain = new ModifierChain();

    var modifierOne = new Modifier({
        align: [0.5, 0.5],
        origin: [0.5, 0.5]
    });

    var modifierTwo = new Modifier({
        transform: Transform.scale(1, 1, 1)
    });
    
    var surface = new Surface({
        size: [100, 100],
        content: "Click to scale surface",
        classes: ["red-bg"],
        properties: {
            textAlign: "center",
        }
    });

    modifierChain.addModifier(modifierOne);
    modifierChain.addModifier(modifierTwo);
    mainContext.add(modifierChain).add(surface);

    surface.on('click', function() {
        modifierTwo.setTransform(Transform.scale(2,2,1),  { duration: 2000, curve: 'easeInOut' });
        surface.setContent('Success!');
    });
});

Can fix it by interchanging order of modifiers in Chain. But not intuitive why an align/origin modifier 
results in translate in this case.

**Comment by jd-carroll** [comment]
I would disagree and say that it is very intuitive, and this is exactly the desired behavior.  IMO, I would avoid using the `ModifierChain` unless you have a very specific purpose you are using it for.

The code:
```
var modifierChain = new ModifierChain();
modifierChain.addModifier(modifierOne);
modifierChain.addModifier(modifierTwo);
mainContext.add(modifierChain).add(surface);
```

Is equivalent to:
```
mainContext
    .add(modifierOne)
    .add(modifierTwo)
    .add(surface);
```

The later is a much more descriptive representation of the graph leading to the surface.

**Comment by neeharik** [comment]
I found that the order of modifiers has to be reversed in the ModifierChain if I want equivalent behavior, as the transforms are not commutative. It appears the ModifierChain applies the transforms in the reverse order of insertion into chain. So the equivalent in the above case seems to be
mainContext
    .add(modifierTwo)
    .add(modifierOne)
    .add(surface);
Is this what you see too? Is this by design?

**Comment by jd-carroll** [comment]
Actually, that is exactly correct.. The modifiers are traversed down to the leaf element (surface) but they are only applied on the way back out.
So yes, the correct equivalent would be:
```
mainContext
    .add(modifierTwo)
    .add(modifierOne)
    .add(surface);
```

**Comment by MylesBorins** [comment]
closing for now.  Please feel free to continue the discussion
