### ISSUE TITLE
Surface Height Auto grow

### ISSUE THREAD

**Issue by groupsvkg** [Famous/famous#589]
Hi Team,

Does Surface height auto grow as the content inside surface grows?

Regards,
vishal
![famous_surface_height](https://cloud.githubusercontent.com/assets/366335/5861097/53376df2-a28c-11e4-9d45-15391e1b537d.png)

**Comment by michaelobriena** [comment]
Hi @groupsvkg!  A Surface size will grow with the content if you use what we call "true" sizing.  In you example, you have size defined as 100px tall (line 8).  If you change that 100 to ```true``` then everything should work as you expect it.

**Comment by groupsvkg** [comment]
Hi Michael,

Does this work's in a scrollView with two views inside having fa-size="[undefined, true]" ?
![famous_scrollview](https://cloud.githubusercontent.com/assets/366335/5863129/46931a90-a29d-11e4-846b-335974fc0f86.png)


Regards,
vishal

**Comment by michaelobriena** [comment]
It should work yes.  I do not know what version of Famo.us, Famo.us Angular is using so cannot comment.  This was however fixed in the main platform.

**Comment by groupsvkg** [comment]
below is my bower.json

{
  "name": "i-collab",
  "version": "0.0.0",
  "dependencies": {
    "angular": ">=1.2.*",
    "json3": "~3.3.1",
    "es5-shim": "~3.0.1",
    "jquery": "~1.11.0",
    "angular-animate": "~1.2.0",
    "angular-resource": ">=1.2.*",
    "angular-cookies": ">=1.2.*",
    "angular-sanitize": ">=1.2.*",
    "font-awesome": ">=4.1.0",
    "lodash": "~2.4.1",
    "angular-socket-io": "~0.6.0",
    "angular-ui-router": "~0.2.10",
    "famous": "master",
    "famous-angular": "master",
    "angular-material": "master",
    "angular-messages": "~1.3.9"
  },
  "devDependencies": {
    "angular-mocks": ">=1.2.*",
    "angular-scenario": ">=1.2.*"
  },
  "resolutions": {
    "angular-animate": "1.3.x",
    "angular": "1.3.x",
    "angular-material": "master",
    "famous": "0.3.4"
  }
}

**Comment by groupsvkg** [comment]
difference attached
![famous_height_true](https://cloud.githubusercontent.com/assets/366335/5863598/b71bc1f6-a2a0-11e4-867b-987d85ca1ae2.png)
![famous_height_76](https://cloud.githubusercontent.com/assets/366335/5863619/e421a1e8-a2a0-11e4-8d8a-0295d72b99b1.png)

**Comment by groupsvkg** [comment]
hi michael,

any update on this?

**Comment by groupsvkg** [comment]
Hi Team,

Any updates on this?

Regards,
vishal

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive an  spirit to the famous engine, which can be found at --> http://github.com/famous/engine
