### ISSUE TITLE
Scrollview height inside flipper 

### ISSUE THREAD

**Issue by istvanskeri** [Famous/famous#591]
I have a full page flipper where each side is a scrollview. The 2nd side of the flipper i have some content that i can only load after the flip function is called. This is where i do an ajax call and with returned data i add a surface to my sequence array.  Sometimes this takes a bit to load this content and because the flip is happening the second side of the flipper does not have height: 100% and i can see the background behind the flipper until that ajax call is done.  Because i can't set the scrollview to 100% height or set the background to be white, how can I fill out the second side of the flipper until that ajax call is finished?

**Comment by talves** [comment]
@istvanskeri You could just use a temporary surface for the back 
`flipper.setBack(tempBackSurface);`
Until the ajax is finished then
`flipper.setBack(ajaxSurface);`

**Comment by TheAlphaNerd** [comment]
closing for now.  please feel free to reopen if your problem was not solved
