### ISSUE TITLE
Add tabindex=-1 in core/Surface so that focus can be controlled via javascript

### ISSUE THREAD

**Issue by steve-the-edwards** [Famous/famous#592]
For keyboard interaction or specific programmatic focus, it would be useful to add tabindex=-1 to the DOM-node underlying core/Surface.  Can this be done, so that a focus() method, similar to that on surface/InputSurface can be used to pass the focus() event to the _currentTarget.  This should rather simply enable javascript control over focus for all surfaces.

**Comment by jd-carroll** [comment]
I'm not overly familiar with `tabIndex`, but maybe this is something best left to an option set on the individual surface.  Something like:

```
if (this.options.tabIndex !== undefined) {
  target.tabIndex = this.options.tabIndex;
}
```

**Comment by TheAlphaNerd** [comment]
you can also set attributes on a surface when it is created

**Comment by MylesBorins** [comment]
closing for now.  Please re open if you are still having trouble
