### ISSUE TITLE
z-translate is ignored by GridLayout view

### ISSUE THREAD

**Issue by Qvatra** [Famous/famous#593]
I believe I've found a bug!
I want to use GridLayout in ScrollView context and be able to translate surfaces of GridLayout in Z-direction. The problem is that for some reason Z-translate is ignored in GridLayout. Seems like GridLayout has zero perspective because translate in x and y directions just work. I did check 3dmatrix of the translated element and it has changed 14th argument but no translation in Z-direction occurs.

see the example here: http://stackoverflow.com/questions/28147595/z-translate-is-ignored-by-gridlayout-view

**Comment by michaelobriena** [comment]
Is it inside of something that has overflow: hidden;

**Comment by Qvatra** [comment]
so what is the solution? As you can see in my code I didn't set any overflow: hidden... 

BTW this code shows black screen in IE which is the second bug

**Comment by michaelobriena** [comment]
@Qvatra I'm sorry but I cannot see any external stylesheets you may have to affect your code so please understand I am trying to help.  There is a known bug that chrome breaks z translations when they occur inside of an element for overflow hidden so I was trying to figure out if that is the case you were running into.

IE does not have preserve3d implemented correctly which makes Famo.us not work.

I will look more into this today when I get into the office.

**Comment by michaelobriena** [comment]
you are 100% right that this is a bug newly introduced in chrome.  It looks like chrome tries to fast path rendering when everything starts at 0 z depth.  I will be filing a chromium bug for this.  For now, adding this should solve your issue.

```js
mainContext
    .add(new StateModifier({
        transform: Transform.translate(0, 0, 100000000),
        size: [1, 1]
    })).add(new Surface({
        properties: {backgroundColor: 'chromeHack'}
    }));
```

**Comment by talves** [comment]
@michaelobriena I always put an initial `Transform.translate` on my modifiers.  Do we need this hack if at least one of the modifiers on the page has a z depth other than 0?

**Comment by michaelobriena** [comment]
It looks like this is only an issue if everything starts at 0 z.

**Comment by jd-carroll** [comment]
@michaelobriena Just to clarify, the workaround is to have *any* DOM element (surface) in a z-plane other than 0 (regardless of any properties).

**Comment by michaelobriena** [comment]
From what I can tell, yes.

**Comment by michaelobriena** [comment]
Closing in favor of https://github.com/Famous/famous/issues/621
