### ISSUE TITLE
gridLayout height inside scrollview

### ISSUE THREAD

**Issue by istvanskeri** [Famous/famous#598]
I have an issue with gridLayout height inside a scrollview. 

I have a scrollview with a surface. I then create a gridLayout with dimensions: [3, 1]. I push that onto scrollview.  I then push another surface onto scrollview. 

Basically the issue is that when i push my gridLayout onto my scrollView it creates a bunch of dead space between the gridLayout and the last surface. It's filling out the rest of the scrollview with the gridLayout stuff even though the gridLayout should only have a height of 30px.

**Comment by istvanskeri** [comment]
I had to create a modifier to set the height of my gridLayout.  

 var gridModifier = new Modifier({
        size: [undefined, 70]
      });
  var renderNode = new RenderNode();
  renderNode.add(gridModifier).add(grid);
  surfacesProfile.push(renderNode);

There has to be a better way

**Comment by michaelobriena** [comment]
Right not there is no better way.  The only other thing would be to manually create a getSize function on the grid layout.

**Comment by solomon-gumball** [comment]
Hey @istvanskeri, gridLayout will create modifiers with sizes for its children based on its own size. 

You could instead use a sequential layout, which is sized by its children.  I know it's a bit late, but here's a Valentine's day themed example -> https://gist.github.com/redwoodfavorite/c3cd4e8f87490480ee6c

**Comment by solomon-gumball** [comment]
Closing this now, but feel free to comment here or reopen this issue if you've still got unanswered questions!
