### ISSUE TITLE
[Question] What is the difference between the "robust" and non-robust implementation?

### ISSUE THREAD

**Issue by jd-carroll** [Famous/famous#604]
In the `PhysicsEngine` there is a section of code commented out that is title "robust integration".

Why is there a single integration call in lieu of the (possible) multiple integration call?  Shouldn't they both derive the same result? (Thus answering my own question).

ref: #602

**Comment by MylesBorins** [comment]
Closing for now.  I am assuming Robust mode will never be enabled.  There is a complete rewrite of the physics system in mixedmode.
