### ISSUE TITLE
Rectangles can't collide with Circles/Other Rectangles

### ISSUE THREAD

**Issue by spraetz** [Famous/famous#605]
Uncertain if this is a bug or intentional, but Rectangles seem pretty silly without this!

**Comment by solomon-gumball** [comment]
Hey @spraetz, it's true that this is the case.  I can tell you that we are currently working on a new physics engine, and 3d box collisions will be a part of that (along with a lot of other cool stuff)!

**Comment by spraetz** [comment]
Awesome!  Right now i'm trying to get something working with physicsJS as the physics engine and Famo.us as the renderer and it's proving... difficult.  and I'm only caring about 2D. 

Is the new physics engine planned for a specific release? or is it just On The Roadmap :tm:  =)
