### ISSUE TITLE
React and Famo.us

### ISSUE THREAD

**Issue by zoomclub** [Famous/famous#606]
ReactJS is on the rise big time! Its time to wakeup and get on the right bandwagon. Where are we going with this? Is the integration ever going to happen? Are we ever ready?

**Comment by michaelobriena** [comment]
Framework integration is something we are not really looking to support at this time.  We are really focused on integrating GL, improving performance, improving our physics offering, improving the API, and reducing bugs.

I think React is a great tool and something I see us having very little trouble integrating with down the road but for the time being this will have to be a community lead project.
