### ISSUE TITLE
XMLHttpRequest cannot load http://code.famo.us/famous/0.3/famous-global.min.js

### ISSUE THREAD

**Issue by speigg** [Famous/famous#610]
Trying to load from the famous CDN with [basketjs](https://github.com/addyosmani/basket.js):

```
XMLHttpRequest cannot load http://code.famo.us/famous/0.3/famous-global.min.js. 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://localhost:3000' is therefore not allowed access.
```

**Comment by jd-carroll** [comment]
@speigg I'm not familiar with basketjs at all, is it possible to put together a codepen that demonstrates this issue?

**Comment by speigg** [comment]
This demonstrates the issue (open the console to see the error): http://jsfiddle.net/fs8rfz1e/

basketjs is just making a GET request to the famous-global.min.js file, and that's what fails, so that's all I put in the jsfiddle.

**Comment by alexanderGugel** [comment]
Interestingly, the jQuery CDN doesn't seem to enable CORS either: http://jsfiddle.net/fs8rfz1e/2/

**Comment by speigg** [comment]
It's probably just an oversight. Script tags don't require CORS, and that's what is used in most cases.

**Comment by marklu** [comment]
Whenever possible, you'll want to load JS via the script tag. The browser already has a mechanism for caching and it's typically not a good idea to interfere with that. The script is loaded once from the CDN and the same copy can work for multiple sites.

If you really want to splice the scripts around and implement caching client-side as with basketjs, you'll want to control the JS. This means not using the CDN.

**Comment by talves** [comment]
@marklu :+1: [CORS knowledge](http://enable-cors.org/) needs to be a requirement for developers.

**Comment by TheAlphaNerd** [comment]
I'm going to close this for now.  At the moment we have no intention of switching on CORS for our CDN.
