### ISSUE TITLE
Chrome Cordova + Crosswalk Tool Chain

### ISSUE THREAD

**Issue by thebigredgeek** [Famous/famous#612]
It might be a good idea to implement a recommended workflow for mobile apps.  For instance, compiling the famo.us app into a chrome cordova + crosswalk container would help avoid cross-browser shenanigans.  Thoughts?

**Comment by michaelobriena** [comment]
Agreed, we should definitely have more resources on the topic.  Maybe a blogpost on this would be a good resource.

**Comment by shupac** [comment]
I'll try to put something together. I built Blossom using the Famo.us Generator, Grunt, Cordova for iOS, and Crosswalk for Android.

**Comment by thebigredgeek** [comment]
Chrome Cordova, IMO, is a no brainer.  There is no reason to use native webkit when Mobile Chrome Apps exists.

**Comment by TheAlphaNerd** [comment]
@thebigredgeek that is a great idea.   We will be putting together a blog post and a video to support this!

**Comment by MylesBorins** [comment]
closing for now.
