### ISSUE TITLE
possible bug: align ImageSurface inside container Surface

### ISSUE THREAD

**Issue by Qvatra** [Famous/famous#614]
I want to do very simple thing: align (to center) small imageSurface in bigger containerSurface with condition that imageSurface will fill the width of the container. My code doesn't work correctly if I add property border: '1px solid black' to the imageSurface. Without adding border everything works fine. Looks like famo.us set align = [0.5, 1] but in code there is align = [0.5, 0.5]. Any ideas?

```js
define(function(require, exports, module) {
    var Engine       = require("famous/core/Engine");
    var StateModifier     = require("famous/modifiers/StateModifier");
    var ContainerSurface     = require("famous/surfaces/ContainerSurface");
    var ImageSurface = require("famous/surfaces/ImageSurface");

    var mainCtx = Engine.createContext();

	var imgCont = new ContainerSurface({
		size: [300,400],
		properties: {
			background: 'red'
		}
	});
    var img = new ImageSurface({
        size: [undefined, true],
        content: 'http://www.shmadrid.com/img/icons/unknown.png',
        properties: {
            border: '1px solid black'
        }
    })
	var imgMod = new StateModifier({
		align: [0.5, 0.5],
		origin: [0.5, 0.5]
	});
	imgCont.add(imgMod).add(img);

    mainCtx.add(new StateModifier({
        align: [.5, .5],
        origin: [.5, .5]
    })).add(imgCont);
});
```

**Comment by michaelobriena** [comment]
This is a bug.  The size of the underlying ImageSurface is not correct which is causing the issues.  The alignment is working, just need to firing a DOM hit to grab the size on load of an imageSurface.

**Comment by Qvatra** [comment]
would wait for a bugfix. please reply/close this post after this bug would be fixed.

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive an  spirit to the famous engine, which can be found at --> http://github.com/famous/engine
