### ISSUE TITLE
Question: Two vertical scrollviews overlaps

### ISSUE THREAD

**Issue by idanwe** [Famous/famous#615]
Hey,

I'm trying to implement view with two vertical scrollviews one on top the other.
I set the layout with `FlexibleLayout` and add two scrollviews.

When the view is render it is looks good
But when I scroll the lower scrollview it is overlaps the first one. see the code pen http://codepen.io/idanwe/pen/WbZpya

How can I achieve that the lower will scroll like hidden overflow and will not cover the view above

**Comment by michaelobriena** [comment]
There is a view called ScrollContainer that does just that.  It wraps it in an extra div so overflow hidden can be used.

**Comment by idanwe** [comment]
Great, thanks!
