### ISSUE TITLE
Can't seem to get Famo.us working with JSPM/SystemJS/AtScript (ES6++)

### ISSUE THREAD

**Issue by thebigredgeek** [Famous/famous#617]
My project is here:

https://github.com/thebigredgeek/famous-timbre-atscript

It's a complete conversion of Timbre.  It starts just fine, except that the menu is located at the bottom of the screen.

Any thoughts?

**Comment by TheAlphaNerd** [comment]
super odd.  I'll take a look at this really soon.

**Comment by jarrodpayne** [comment]
Same issue here. Can't quite figure out what's going on. Too new to jspm

**Comment by MylesBorins** [comment]
This should be working now. We got rid of the sec folder in the published
version

**Comment by thebigredgeek** [comment]
Can you advise on how to integrate this fix into my project?   Maybe you could put in a PR or something?  Thanks Myles

**Comment by MylesBorins** [comment]
@thebigredgeek it looks to me like jspm is not set up properly.  Curious as to why you are installing famo.us via jspm vs via npm

**Comment by jarrodpayne** [comment]
@TheAlphaNerd jspm is my preference for front-end js assets. Unless, of course, it can't be supported.

**Comment by jarrodpayne** [comment]
@thebigredgeek I finally got this working using the jspm override config feature in the CLI

```
jspm install --save github:Famous/famous -o "{
  format: 'amd',
  shim: {
    '*/*': {
      deps: ['../core/famous.css!']
    }
  },
  dependencies: {
    css: '^0.1.0'
  },
  directories: {
    lib: 'src'
  }
}"
```

**Comment by capaj** [comment]
@jpdesigndev actually jspm has famous override in it's own registry, so proper way of installing is

```
jspm install famous
```

**Comment by jarrodpayne** [comment]
@capaj It looks like they just added something that will work 2 days ago. https://github.com/jspm/registry/blob/master/package-overrides/github/Famous/famous%400.3.5.json

**Comment by jarrodpayne** [comment]
Also, pay careful attention to their `directories` object ([lines 3-5](https://github.com/jspm/registry/blob/master/package-overrides/github/Famous/famous%400.3.5.json#L3-L5)). It exposes the `dist` folder which may not be desired. It depends on your needs. I'm using ES6 modules with JSPM/SystemJS (as is likely the case with the people interested in this issue), so I prefer the src files so I can import modules as needed.

**Comment by thebigredgeek** [comment]
@TheAlphaNerd `npm` is definitely losing market share regarding the front-end, in lieu of tools like `bower` and `jspm`.  Especially with ES6 become more widely used... it has a module loading syntax that isn't CommonJS

**Comment by MylesBorins** [comment]
closing for now. Published version to npm in common, should not be causing a problem

**Comment by gnimmelf** [comment]
Still problems (maybe just my inexperience), since this fix does not allow for direct import of famo.us sub-modules as `import 'famous/inputs/FastClick'`. 

I can work around that by importing the global and then setting vars by dotting into the main object, but other packages (eg pilwon/react-famous and IjzerenHein/famous-sizeconstraint) that rely on the direct imports fail.

I would assume that making all the famo.us sub-modules available for direct import would be desierable, as that would also minimize the build by not including unused sub-modules?

Suggestions?
