### ISSUE TITLE
why are you accessing private members in fomo.us examples?

### ISSUE THREAD

**Issue by Qvatra** [Famous/famous#618]
I was looking at your example (examples/core/view) and have found weird thing like accessing private members _eventInput and _add:

    var view = new View();
    var surface = new Surface();
    surface.pipe(view);

    view._eventInput.on("click", function() {
        alert("Primary Surface Clicked");
    });

I did try to rewrite it as:

    view.on("click", function() {
        alert("Primary Surface Clicked");
    });

but it doesn't work. 
I don't understand how should I use event piping between view and a surface.
Accessing private members looks like workaround or something...

**Comment by michaelobriena** [comment]
This was intended behavior but has only confused most of our users.

The thinking was around preserving the maximum amount of consumability.  If you can affect how the View behaves to "click" events it receives, then you have changed the implementation of that View.  This means we could both have the same CustomView in our application that does wildly different things when it receives the click ever.  ".on" at the View level, is actually when the View emits a click event.
