### ISSUE TITLE
Surface list with line wrapping

### ISSUE THREAD

**Issue by vplifer** [Famous/famous#619]
Hello.

I am trying to implement tag list, that should look like this:

[famo.us]   [meteor]  [todo]
[problems]   [articles]
[features]   [foo] [double-foo]

And I need each tag to be a surface, so I can drag it in famo.us way. 

`SequentialLayout` can't be wrapped.
`GridLayout` has equal size for each cell.

Is there a way to do this? Or the only way is to create custom view?

Thank's.

**Comment by michaelobriena** [comment]
Hi @vplifer,

Not sure if I completely understand the question but most of the time, having a custom View that controls the modifiers for subviews/Surfaces is the best approach.   The premade layouts are great at easily defining some simple layouts but handrolling stuff is generally the best approach.  You can then use the sync library to turn mouse/touch data into dragging.

**Comment by vplifer** [comment]
Okay.

I just thought that there is out of the box solution, that I missed.

Thanks.
