### ISSUE TITLE
Bug: Chrome Z-Translation

### ISSUE THREAD

**Issue by michaelobriena** [Famous/famous#621]
When everything on the page starts with a z-translation of 0, subsequent transform changes are ignore.  I am assuming this is because Chrome is trying to fast path some of the rendering pipeline.  A fix has been issued and we hope to have this resolved browser side.

**Comment by jd-carroll** [comment]
Is there is a related Chromium bug?
label: vendor bug

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive an  spirit to the famous engine, which can be found at --> http://github.com/famous/engine
