### ISSUE TITLE
concurrent modifiers result in huge surface trembling in famo.us

### ISSUE THREAD

**Issue by Qvatra** [Famous/famous#627]
My goal is to mimic Z-translation in perspective mode by using multiple modifiers. I can not use just z-translation of a surface because a text of translated surface became blurred (at least at Chrome but also on another browsers). The idea of using concurrent modifiers is explained in my blog: https://ozinchenko.wordpress.com/2015/02/04/how-to-avoid-blurring-of-the-text-in-famo-us-during-transition-in-z-direction/

the codepen code is here: http://codepen.io/Qvatra/pen/yyPMyK?editors=001

Why do I have the shaking of the image? How to avoid that?

**Comment by the-reality-engineer** [comment]
Transitioning the size is actually really bad for performance. It causes the surface to be redrawn every frame.

**Comment by michaelobriena** [comment]
The only way to get around the blurry text is to understand your place in the animation and toggle the font size accordingly.

As @speigg mentioned, this might have to do with the repainting the browser has to do.

**Comment by talves** [comment]
@michaelobriena if you see in the codepen, @Qvatra is transitioning the `StateModifier` that resizes the surface and using the `setSize` on the surface at the same time. That is the reason for the tremble on the surface. I explained this on a StackOverflow question also.

**Comment by MylesBorins** [comment]
double dip

**Comment by MylesBorins** [comment]
closing for now as it seems that @talves has solved the mystery.

If I am mistaken please reopen
