### ISSUE TITLE
[ScrollView] goToPage an extra page

### ISSUE THREAD

**Issue by fmoutawe** [Famous/famous#628]
Hello,

I made a simple pager behind the scrollview with index indicator.
When user tap/click on an index, scrollview move to the index number.
If user tap/click on current+3 index, scrollview break down.

**Comment by MylesBorins** [comment]
@wgester thoughts?

**Comment by solomon-gumball** [comment]
Hey ivelfan, do you think you could put together a codepen demo or something? I can't seem to recreate the issue on my own.

:+1:

**Comment by MylesBorins** [comment]
closing for now.  Please re open if you have an example
