### ISSUE TITLE
Scrollview's setPosition() and setVelocity() doesn't always work when at the top or bottom of a scroll view

### ISSUE THREAD

**Issue by koflaherty** [Famous/famous#630]
When a scrollview is on the edge of its content, the top or bottom of the scroll view, the setPosition() or setVelocity() functions won't perform correctly if the previous scroll direction was opposite to that of the new scroll direction.

I've made the following codepen to show the issue. http://codepen.io/anon/pen/yyoodN

Basically I'm trying to program a scroll to bottom, or lock to bottom with new content coming into the scroll view.

Note: Was told this is not an angular problem and to post it here!

**Comment by solomon-gumball** [comment]
Thanks for pointing out this issue, it has to do with the how springs are attached and detached at the end of the scrollview.  We should have a fix in shortly.

**Comment by koflaherty** [comment]
Excellent thank you!

**Comment by MylesBorins** [comment]
Closing assuming the fix landed. Please reopen if i am mistaken
