### ISSUE TITLE
Famous integration into WordPress

### ISSUE THREAD

**Issue by miquael** [Famous/famous#635]
I want to install a Famous UI into a WordPress page.  Where do the all the JS, content, and lib files go relative to the WordPress directory?

Anyone have experience with this?

**Comment by solomon-gumball** [comment]
@FarhadG

**Comment by FarhadG** [comment]
Hey there,

It depends on your theme directory. Earlier this year, we used a theme and then used the 'child themes' strategy within Wordpress to modify the theme to our needs. In doing so, you can include the necessary JS and dependencies within the theme directory. Let me know if that answers your question or if you need further assistance.

**Comment by miquael** [comment]
Hey there Farhad,

Thanks for the tip.  We are using the The7 theme, and are working from a child of that theme.  

What JS dependencies go into that child theme, and how?  Happen to have an example?

**Comment by MylesBorins** [comment]
closing for now.  Please keep the conversation going if you are still having trouble.
