### ISSUE TITLE
What's the reasoning for suppressing touch events by default? Question

### ISSUE THREAD

**Issue by omasri** [Famous/famous#636]
I tried to look at the famo.us university on my iPad and I couldn't scroll the page. http://famo.us/university/home/#/

After reading the issues I noticed similar posts in which the solution was to remove the code suppressing the touch events.

Why are the events being suppressed?  What breaks if you turn them on?

**Comment by MylesBorins** [comment]
University is not supported on mobile.  Sorry you are having trouble.  Our next version should have some degree of mobile support for reference documentation.
