### ISSUE TITLE
force/VectorField has a bug 

### ISSUE THREAD

**Issue by aaronwwf** [Famous/famous#638]
VectorField.prototype.setOptions = function setOptions(options) {
        if (options.strength !== undefined) this.options.strength = options.strength;
        if (options.direction !== undefined) this.options.direction = options.direction;
        if (options.field !== undefined) {
            this.options.field = options.field;
            _setFieldOptions.call(this, this.options.field);
        }
    };

that has a bug ,should be like this:

VectorField.prototype.setOptions = function setOptions(options) {
        if (options.strength !== undefined) this.options.strength = options.strength;
        if (options.direction !== undefined) this.options.direction = options.direction;
        if (options.position !== undefined) this.options.position = options.position;
        if (options.field !== undefined) {
            this.options.field = options.field;
            _setFieldOptions.call(this, this.options.field);
        }
    };

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive an  spirit to the famous engine, which can be found at --> http://github.com/famous/engine
