### ISSUE TITLE
Is there any extend() method?

### ISSUE THREAD

**Issue by adriano-di-giovanni** [Famous/famous#640]
I'm a famo.us newbie trying to write my first component. I couldn't find an extend() method. Did I miss it?

Thanks in advance,
Adriano

**Comment by alexanderGugel** [comment]
Hey Adriano,

no. There is no extend method. We use `Object.create` in order to set up the prototype chain directly throughout the framework. If you prefer using `extend`, you could simply use [Underscore](http://underscorejs.org/) or [lodash](https://lodash.com/).

## Example 1 using `Object.create`

``` javascript
function MyView() {
    View.call(this);
}

MyView.prototype = Object.create(View.prototype);
MyView.prototype.constructor = MyView;

...
```

## Example 2 using `extend`

``` javascript
function MyView() {
    View.call(this);
}

_.extend(MyView.prototype, View.prototype);
```

The `extend` method does not exist on the View prototype, therefore `View.extend({})` won't work.

There is also an example on how to use Views: https://github.com/Famous/famous/blob/develop/examples/core/View/example.js

**Comment by adriano-di-giovanni** [comment]
Thanks for your reply, @alexanderGugel 

I mean something like a Backbone style extend

``` javascript
define([ 'famous/core/View' ], function (View) {

  var
    prototypeProperties = {
      initialize: function () {
        // ...
      }
    },
    staticProperties = {};

  var
    MyView = View.extend(prototypeProperties, staticProperties);

  return MyView;
});
```

I'd like to know if you think it could be useful and you plan to implement it or if you think it would not be worth it.

Thanks in advance,
Adriano

**Comment by alexanderGugel** [comment]
I don't think helper utilities for setting up the prototype chain belong in famous. That being said, I totally agree that `View.extend()` is much more intuitive than manually setting up the prototype chain. If you prefer having an extend method on Views, just add it!

``` javascript
  // Helpers
  // -------

  // Helper function to correctly set up the prototype chain, for subclasses.
  // Similar to `goog.inherits`, but uses a hash of prototype properties and
  // class properties to be extended.
  var extend = function(protoProps, staticProps) {
    var parent = this;
    var child;

    // The constructor function for the new subclass is either defined by you
    // (the "constructor" property in your `extend` definition), or defaulted
    // by us to simply call the parent's constructor.
    if (protoProps && _.has(protoProps, 'constructor')) {
      child = protoProps.constructor;
    } else {
      child = function(){ return parent.apply(this, arguments); };
    }

    // Add static properties to the constructor function, if supplied.
    _.extend(child, parent, staticProps);

    // Set the prototype chain to inherit from `parent`, without calling
    // `parent`'s constructor function.
    var Surrogate = function(){ this.constructor = child; };
    Surrogate.prototype = parent.prototype;
    child.prototype = new Surrogate;

    // Add prototype properties (instance properties) to the subclass,
    // if supplied.
    if (protoProps) _.extend(child.prototype, protoProps);

    // Set a convenience property in case the parent's prototype is needed
    // later.
    child.__super__ = parent.prototype;

    return child;
  };

  View.extend = extend;
```

(Stolen from [Backbone](http://backbonejs.org/docs/backbone.html#section-228))

This implementation relies on Underscores extend method, but you could also simply use your own `extend` method (actually, you don't even need to be able to extend by multiple objects):

``` javascript
var _  = {};
_.extend = function extend(obj) {
    Array.prototype.slice.call(arguments, 1).forEach(function(source) {
        if (source) {
            for (var prop in source) {
                obj[prop] = source[prop];
            }
        }
    });

    return obj;
};
```

I didn't try this out, but it should work.

**Comment by adriano-di-giovanni** [comment]
Thanks a lot, @alexanderGugel
