### ISSUE TITLE
ScrollView breaks while keyboard is open on iOS

### ISSUE THREAD

**Issue by lukifer** [Famous/famous#641]
Scrolling in Mobile Safari goes wonky while an <input> or an InputSurface has keyboard focus. See examples: 

http://jsfiddle.net/byC98/12/
http://jsfiddle.net/byC98/13/

**Comment by lukifer** [comment]
Following up, anybody had a chance to look at this yet? It's a major show-stopper on an otherwise production-ready app.

/cc @wgester 
/cc @TheAlphaNerd

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive and spirit to the famous engine, which can be found at --> http://github.com/famous/engine
