### ISSUE TITLE
Core development transparency 

### ISSUE THREAD

**Issue by andrewreedy** [Famous/famous#642]
It would be nice to have some transparency, like a Trello board or some type of internal development road map, so that developers who use Famo.us could plan accordingly. I know Famo.us is scaling up and opened a new office, but it seems like releases haven't been very frequent and we haven't heard any additional information on things like Famo.us Carousel, Famo.us UI Components, or any updates on how mixed-mode is going.

**Comment by KerimG** [comment]
Second this. Am reluctant to use or contrinute to the famo.us framework, because of how opaque development is. 

There are people on reddit fearing that the project might be dead.

On February 26, 2015 7:23:05 PM CET, Andrew Reedy notifications@github.com wrote:

> It would be nice to have some transparency, like a Trello board or some
> type of internal development road map, so that developers who use
> Famo.us could plan accordingly. I know Famo.us is scaling up and opened
> a new office, but it seems like releases haven't been very frequent and
> we haven't heard any additional information on things like Famo.us
> Carousel, Famo.us UI Components, or any updates on how mixed-mode is
> going. 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Famous/famous/issues/642

## 

Sent from my phone. Please excuse my brevity.

**Comment by andrewreedy** [comment]
@KerimG It's definitely not dead. They just raised around 25 mill in this last round, so I imagine they are going through a rapid growth period. However, they shouldn't leave their early adopters hanging for so long.

**Comment by KerimG** [comment]
That's very reassuring. Would you mind linking to that info? Just want to read out of curiosity.

Definitely agree with your last point.

On February 26, 2015 7:47:41 PM CET, Andrew Reedy notifications@github.com wrote:

> @KerimG It's definitely not dead. They just raised around 25 mill in
> this last round, so I imagine they are going through a rapid growth
> period. However, they shouldn't leave their early adopters hanging for
> so long.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Famous/famous/issues/642#issuecomment-76241159

## 

Sent from my phone. Please excuse my brevity.

**Comment by andrewreedy** [comment]
@KerimG http://venturebeat.com/2014/08/13/famo-us-raises-25m-to-double-down-on-javascript-app-development-framework/

**Comment by MylesBorins** [comment]
Hey All,

Myles here, I am a famo.us employee and the release manager of this repo.  A bit of clarity.

The project is most definitely not dead.  We have had most of our staff working diligently on the problem of dealing with Dom + GL in a single context, most of you know this project as "MixedMode".

Just this week we have begun an internal alpha with two partnering companies who are testing out the API and seeing how things work.  We are also in the process of revamping all of our documentation and university to support the new platform.

The problem with treating Dom + GL in a single context has required a different approach to API, and as such you can expect to see some fairly radical changes in the next version.  We will be releasing it publicly in June at the [jQuerySF](jquerysf.com) conference.

We are in the process of designing a graceful end of life to the current api.  If you take a look at the [next branch[(https://github.com/famous/famous/tree/next) you will see that the last commit (UNIT TESTS!!!!) landed just a week ago.

The biggest problem we have had is that we rapidly hired quite a few engineers to support the MixedMode project, and did not have many individuals who were able to support the older version of the platform.  @michaelobriena has been pivotal in keeping 0.3.x alive, but he is also the Lead Platform Engineer on MixedMode, and balancing both projects can be very difficult.

As for myself, I am the release manager, and have had quite a few other responsibilities dropped on my plate such as curating jQuerySF and running famo.us labs, which has made it difficult to give the platform the same attention I had in prior months.

I do think it is worth mentioning that we have been fairly consistent in releasing a cut of the platform around once a month, although I definitely see how that pace is frustrating.

So what do you have to be excited about?  In the coming months a brand new, more powerful, version of the platform will be available publicly.  We will have a decently sized engineering team that has been working at it non stop for the last 6 months, and are ready to fully support it.  The new platform is not only faster, but it is modular!!!  This is completely different from our 0.1 / 0.2 days when "modular" meant git modules with leaky peer / circular dependencies.  The new platform is comprised of modules that are individually unit tested, and could very well be consumed outside of the platform if you so desired (GL primitives / math!!!).

I apologize that things have felt dark.  It is my job as head of community / developer relations to make sure that the community knows what is going on, and knows that Famo.us has their backs.  I have had so many things to do in the last few months that I have not fulfilled that obligation, and for that I am truly sorry.

What I can promise you is that I spend every day in this office working for our developers.  I will personally make sure that no one is left hanging.  If you have any concerns please email me and I will find time to chat via irc / google hangouts / famo.us demo day / whatever works best. My email address is myles [at] famo.us

I will be speaking tonight at the LA Famo.us meetup, and talking to quite a few of these concerns.  I am not sure if it is being live streamed, but I do believe it is being filmed.  I will do my best to make sure you all get a chance to see this recording, hopefully it will answer more questions

**Comment by andrewreedy** [comment]
Hey Myles, I'm sure everyone really appreciates this update!! I kept checking the Famo.us blog, hoping for some sort of update and it just never came, so this is definitely reassuring! Scaling a team that quickly and switching gears to a new product at the same time must be quite the undertaking so no worries on the past few months. I hope going forward we have more frequent updates on development progress and maybe sneak peaks into some of the API's we can look forward to. Some of us have apps that use Famo.us in production so updates like this is crucial to making the decision of whether to stick with the platform or not.  I'm excited to hear more from your talk tonight (I won't be able to make it up to LA but I'll check the recording). Keep up the momentum!! A modular platform with tests sounds much better :+1:. I'm excited to see the performance of the new platform!

**Comment by andrewreedy** [comment]
Alongside a Tello or some type of public roadmap, a [gitter](https://gitter.im/) might be nice! You can paste a link at the top of your readme. It seems to be catching on with other open source frameworks.

**Comment by trusktr** [comment]
if (Gitter) {
  @TheAlphaNerd .awesome = true;
}

**Comment by talves** [comment]
@trusktr @andrewreedy  having another chat would just be another place that Famo.us has no time to contribute in my opinion.  Although, I do like the idea of Gitter.  

Another issue is that I would rather spend my time discussing the REAL release of Famo.us ("Mixed Mode").  I spent a lot of time helping out on IRC and that ended up being a boon now that the current version will have an end of life.  We have no access to the current mixed mode that will be integrated with jQuery. Famo.us is not really developed as open source at this point, so what would we discuss?

**Comment by MylesBorins** [comment]
I can't say too much. But there is a chance this will all be sorted much
sooner than later

**Comment by talves** [comment]
:heart_eyes: @TheAlphaNerd Sooner than June? :tada:

**Comment by pilwon** [comment]
Gitter :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by pilwon** [comment]
@TheAlphaNerd Is the recording of LA meetup available anywhere?

:heart_eyes: Gitter :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by dcworldwide** [comment]
Any updates?

**Comment by trusktr** [comment]
@dcworldwide I have a feeling check back on Thursday.

**Comment by dcworldwide** [comment]
@trusktr woo! Feeling hopeful for some direction

**Comment by trusktr** [comment]
Entirely open development is beneficial for a community around a project because if all development were to happen in a public repo instead of a private one, speed of development for the project would be faster due to people knowing what the latest code changes are and thus having the ability to make informed and meaningful PRs. I have a feeling that, currently, people (i.e. me) may not want to make PRs based on code that is outdated because making those PRs will be a waste of precious time. Plus, who knows, people in the community might have great ideas that the Famo.us team hasn't thought of yet.

@marklu @michaelobriena

**Comment by konukk** [comment]
@trusktr  +1

**Comment by LeJPR** [comment]
+1 for getting some further info on the direction with the new API - having been developing with the current version (understanding that its an early release and doing so at our own risk) it would be good to get some further info on the upcoming release - currently feels like us early adopters are being left in the dark!

**Comment by MylesBorins** [comment]
closing for now.  Expect some newsletters in the near future explaining everything, followed by a clearer more transparent road map.
