### ISSUE TITLE
scrollview behaves oddly after items are removed

### ISSUE THREAD

**Issue by fractallian** [Famous/famous#644]
Appears to be due to the fact that ViewSequence.Backing.prototype.calculateSize doesn't trim the calculatedSizes array when items are removed so scrollview._scroller.getCumulativeSize() returns the old, larger size. My fix is to put this.calculatedSizes = [[0,0]; at the top of Backing.prototype.calculateSize but unsure if this will have other undesired effects.

**Comment by AlessandroAnnini** [comment]
Hi guys, any news about this one?
thank you!

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive and spirit to the famous engine, which can be found at --> http://github.com/famous/engine
