### ISSUE TITLE
EventEmitter.prototype.removeListener (and Timer.setTimeout) are broken

### ISSUE THREAD

**Issue by the-reality-engineer** [Famous/famous#645]
More specifically, this pattern is currently broken: 

``` javascript
object.on('event', function handler() {
   // do something
   object.removeListener('event', handler)
})
```

And here is a more concrete example

``` javascript
    var Engine = Famous.Core.Engine;

    Engine.on('test', function handler1() {
        alert('1')
        Engine.removeListener('test', handler1)
    })

    Engine.on('test', function handler2() {
        alert('2')
        Engine.removeListener('test', handler2)
    })

    Engine.on('test', function handler3() {
        alert('3')
        Engine.removeListener('test', handler3)
    })

    Engine.on('test', function handler4() {
        alert('4')
        Engine.removeListener('test', handler4)
    })

    Engine.emit('test')
```

The expected output is 4 alerts:
1
2
3
4

The actual output is 2 alerts:
1
3

Here is the live example:  http://jsfiddle.net/m5btLo35/3/

The problem is that `EventEmitter.prototype.removeListener` is removing a listener from an array of listeners while the EventEmitter is emitting events to the listeners in that same array. This becomes a problem whenever there is more than one listener attached, as all handlers do not receive an event. The correct implementation would require removeListener to mark the handlers that should be removed, and then remove them only after the event emitter is no longer iterating through it's listeners. 

This pattern is currently used in `Timer.setTimeout` (which will causes timers to fire out of sequence and in an increasingly delayed fashion if there are many of them, as demonstrated here: http://jsfiddle.net/vdz8bkd8/8/).

**Comment by MylesBorins** [comment]
@michaelobriena

**Comment by wangxiao** [comment]
try this https://github.com/leancloud/leanevent

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive and spirit to the famous engine, which can be found at --> http://github.com/famous/engine
