### ISSUE TITLE
square surface - proportions

### ISSUE THREAD

**Issue by djindjic** [Famous/famous#646]
Could you allow or is there any way to ensure that surface modified by proportions attribute will always be square and not rectangle?

Something like:

``` js
proportions: [undefined, 0.5]
```

or

``` js
proportions: [0.5, undefined]
```

**Comment by MylesBorins** [comment]
Unfortunately I do not believe this is currently possible.  If I recall correctly undefined relies on the underlying default layout.  If you wanted to force proportionality you might want to implement a proportionalSurface that has the desired behaviour.

/cc @michaelobriena

**Comment by djindjic** [comment]
thanks @TheAlphaNerd. do you have any example code for proportionalSurface? I cant find it in docs.

**Comment by MylesBorins** [comment]
It does not exist. I was more implying that one could be implemented.

**Comment by djindjic** [comment]
I found a great solution. If anybody find this issue by search engine it could be worth to paste a link here:

https://github.com/IjzerenHein/famous-sizeconstraint
