### ISSUE TITLE
InputSurface - First character input displayed twice

### ISSUE THREAD

**Issue by groupsvkg** [Famous/famous#647]
Hi Team,

On samsung grand chrome browser first character in InputSurface gets displayed twice.

var inputSurface = new InputSurface({
    size: [undefined,50],
       value: '',
    properties: {
        borderColor: 'red',
        padding: 0,
        color: 'green'
    }
});
Regards,
vishal

**Comment by MylesBorins** [comment]
That is SUPER WEIRD... we don't have one of these devices to test on AFAIK.  @michaelobriena have you heard of this ever happening before?

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive and spirit to the famous engine, which can be found at --> http://github.com/famous/engine
