### ISSUE TITLE
proportions does not apply child nodes

### ISSUE THREAD

**Issue by djindjic** [Famous/famous#649]
I have surface scale animated with:

``` js
var Engine = require('famous/core/Engine');
var Surface = require('famous/core/Surface');

var mainContext = Engine.createContext();

var firstSurface = new Surface({
  content: "<h3>Hi!</h3><p>I'm a surface!<br>I live inside a context.</p><p>You can add <b>HTML</b> content to me and style me with <b>CSS!</b></p>",
  size: [undefined, undefined],
  properties: {
    backgroundColor: 'rgb(240, 238, 233)',
    textAlign: 'center',
  }
});

var drawScaleModifier = new Modifier();
var transitionable = new Transitionable([0, 0]);
transitionable.set([0.5, 0.5], { duration: 1000 });

drawScaleModifier.proportionsFrom(function() {
  return transitionable.get();
});

mainContext.add(drawScaleModifier).add(firstSurface);
```

and surface itself is animated fine to 50% of parent size, but surface content (text in this case) does not scales and have same size no matter how big is surface.

**Comment by MylesBorins** [comment]
@michaelobriena ?

**Comment by djindjic** [comment]
@michaelobriena :cake:

**Comment by michaelobriena** [comment]
This is expected behavior.  We are just defining the size of that outer Surface.  From there, you either would need to have the HTML/CSS responsible for the inner Surface styling or add another node to your scene graph that has the size changing part as a parent and it has and origin/align of [.5, .5].

**Comment by djindjic** [comment]
I could add another node to my scene, but again, text in that node will not be scaled by animation changes. Also, I cant find any elegant html/css solution as famous are. I found view port scaling but it depends on windows size... I need some TextSurface but not Textarea.

**Comment by djindjic** [comment]
@michaelobriena @TheAlphaNerd I've just tried with TextareaSurface and area is scaled fine, but text in area is with same size throw all animation :(

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive and spirit to the famous engine, which can be found at --> http://github.com/famous/engine

**Comment by djindjic** [comment]
@TheAlphaNerd it's better news then a fixed issue! Thanks guys, I hope that engine will be great tool!
