### ISSUE TITLE
Famo.us Inspector (dev tool feature request)

### ISSUE THREAD

**Issue by andrewreedy** [Famous/famous#650]
Since inspecting the Dom in Famo.us isn't as useful as it is when you are manipulating the Dom directly, it would be really helpful to be able to inspect the render tree / Famo.us hierarchy.

```
<Context>
  <RenderController>
    <Scrollview>
      <Surface></Surface>
      <Surface></Surface>
      <Surface></Surface>
    <Scrollview>
  </RenderController>
</Context>
```

**Comment by MylesBorins** [comment]
This is a great idea. I think the conversation might be better suited for the google group. Closing for now.
