### ISSUE TITLE
White gap appearing when keyboard is open

### ISSUE THREAD

**Issue by Carlosriverae** [Famous/famous#655]
I have an app ( Requested on iPhone & Android ). When a user tries to register he clicks on certain input fields. The problem is that a huge white gap appears above the keyboard and hides half my app. Only tested this on Nexus 5/6.

![requestedbug](https://cloud.githubusercontent.com/assets/1417867/6566284/45d7a0d4-c675-11e4-906b-3eb2b7f7b7f5.png)

You can test it by downloading the app ( https://play.google.com/store/apps/details?id=com.requestedapp ), try to register and see the bug live.

I've tried the body { position: absolute } fix but it makes it very difficult to select some of the lower fields.
Any help is greatly appreciated!

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive and spirit to the famous engine, which can be found at --> http://github.com/famous/engine
