### ISSUE TITLE
Performance issues with Matrix "digital rain"

### ISSUE THREAD

**Issue by srazzaque** [Famous/famous#656]
Hi all,

I decided to write something that would really give famo.us a performance stress-test. I'm wondering if anyone can give me any pointers to getting "digital rain" to perform better. It starts at a cool 60fps, but then grinds down to around 5fps in Chrome. On Firefox it basically doesn't work at all.

I wrote the initial version in ClojureScript, but then re-wrote it in JavaScript in order to submit it here. The link to the code is over here:

https://github.com/srazzaque/digital-rain/blob/master/resources/public/js-raw/app.js

And an online version is over here:

http://srazzaque.github.io/digital-rain/index-purejs.html

The better and more dynamic ClojureScript version is here (it's a little more random in nature due to the easier semantics provided by core.async):

http://srazzaque.github.io/digital-rain/index.html

Any help getting this guy to perform would be greatly appreciated!

Cheers,
SR

**Comment by talves** [comment]
@srazzaque I played with this a bit and made some changes for fun.

The performance is definitely dependent on the number of Elements you are animating at a time. 
100 columns x 60 rows = 6000 DOM elements on the page.  That  is a lot of items being transitioned at a time.  [Although changing opacity is a fairly cheap animation](http://www.html5rocks.com/en/tutorials/speed/high-performance-animations/), doing it on many elements at the same time will still cause a performance hit.

I believe "MixedMode" will help with making the performance a lot better when it is released.

[Here is one iteration of my changes.](http://jsbin.com/duduzo/1/edit?js,output)

Here are some of the items I changed that had a change on performance:
- **Only set content of each surface at the beginning, not prior to each animation start**
- **Brought opacity to zero (0) on final transition**

**Comment by srazzaque** [comment]
@talves Thanks! Yes, the number of nodes definitely had the largest (visible) impact on the performance, I'll find a way to work this inspiration back into my CLJS code.

Definitely keen on putting MixedMode to the test once released :-)

**Comment by pkpkpk** [comment]
@srazzaque have you seen http://swannodette.github.io/2013/08/02/100000-dom-updates/ ?
