### ISSUE TITLE
SequentialLayout#sequenceFrom vs FlexibleLayout#sequenceFrom

### ISSUE THREAD

**Issue by adriano-di-giovanni** [Famous/famous#658]
The `items` param of `SequentialLayout#sequenceFrom` can be of types `Array|ViewSequence`.
The `sequence` param of `FlexibleLayout#sequenceFrom` can be of type `Array` only.

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive and spirit to the famous engine, which can be found at --> http://github.com/famous/engine
