### ISSUE TITLE
Missing Easing Curves for `outIn`

### ISSUE THREAD

**Issue by rjmoggach** [Famous/famous#659]
Would be great to add `outIn` easing curves in addition to `inOut`

**eg.**

```
    /**
     * @property outInExpo
     * @static
     */
    outInExpo: function(t) {
        if(t<.5) return Easing.outExpo(t*2)*.5;
        return Easing.inExpo(t*2-1)*.5+.5;
    },
```

May be a bit more involved for Back, Elastic, etc. but most can use something like the above I imagine??

At the moment I'm doing something like this...

```
var outInEasing;
outInEasing = function(inCrv, outCrv, t) {
  if (t < .5) return outCrv((t * 2) * .5);
  return inCrv(t * 2 - 1) * .5 + .5;
};
```

> haven't tested above code...

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive and spirit to the famous engine, which can be found at --> http://github.com/famous/engine

Please feel free to see if we need that same easing curve over there!
