### ISSUE TITLE
famous.js, react.js with ClojureScript

### ISSUE THREAD

**Issue by sonwh98** [Famous/famous#661]
Has anyone attempted to use famous.js from ClojureScript?  I'm currently using ClojureScript and Reagent (Clojurescript for React.js) and would like to integrate famous.  Are there any examples?

**Comment by pkpkpk** [comment]
I have a famous jar on clojars, I just published the repo here https://github.com/idiotslowdown/famous-cljs

I have not used it with react yet... probably worth dissecting the famous-react integration repo.

**Comment by luposlip** [comment]
@sonwh98 did you find any way to do this? I'm looking for the same solution.

**Comment by sonwh98** [comment]
@luposlip no integration with react/reagent but take a look at @pkillean repo. He has working examples of using famous as javascript interop.

**Comment by luposlip** [comment]
Thanks @sonwh98, will take a look at it!
