### ISSUE TITLE
Lightbox template

### ISSUE THREAD

**Issue by cliren** [Famous/famous#663]
Lightbox widget is a nice design pattern that can fit many applications. We are building a mobile app and really liked the interface http://codepen.io/befamous/pen/kbxnH. How can we build this using famo angular? Are there any examples of lightbox using famo-angular? We are fine going native famo.us if we get access to source code of lightbox demo. 

Getting started is easy following the university but building complex applications requires some building block examples. Why not provide some examples components which can be reused by projects?

**Comment by MylesBorins** [comment]
We have not created a famous angular component for the light box in that code pen example.  In fact the example is so old it doesn't even work with the latest version of the platform.  Indeed building larger applications are difficult, and that is a problem that we are hard at work on solving internally.

For now though there is no silver bullet we can give you to solve your technical problem.  If you are inspired by the lightbox, we highly suggest you channel that inspiration and attempt to implement something similar.

Please feel free to ask any more questions you might have.
