### ISSUE TITLE
Famo.us not supported in android browsers.

### ISSUE THREAD

**Issue by pranalivc** [Famous/famous#666]
I am trying load the app created using Famo.us in android phones's default browser but the page is displaying bank(white).
       As in docs with link http://famo.us/docs/reference/pages/0.3/browser-and-device-support.html Browsers and Device specification it is written as it will support in "Android phones: Nexus 4, Nexus 5, Nexus 6, Moto G" which are chrome supported  and browsers like "Chrome, Firefox, Safari, IE11+". But what about android browses??? 
        Even the application apk working in android 4.4.4(Sony experia-z) but not working in android 4.2.2(Sony experia-C ). 
      Some transitions and rotation animation running  in chrome nicely in higher android devices but not in lower one like Sony experia-C. What is the solution for this??

**Comment by pranalivc** [comment]
@jordanpapaleo please answer...

**Comment by MylesBorins** [comment]
Famo.us is not supported in older phone browsers.  As such we suggest using crosswalk to build for earlier models using a plugable webview.
