### ISSUE TITLE
Textarea can't be scrolled on mobile

### ISSUE THREAD

**Issue by remcoanker** [Famous/famous#667]
Textareas can't be scrolled on mobile when they overflow, as seen in this fiddle: http://jsfiddle.net/jnwxj8c9/1/ (try it on mobile or chrome device mode with touch screen emulation)

The problem is in Engine.js, [this line](https://github.com/Famous/famous/blob/develop/src/core/Engine.js#L138).

I fixed it by changing it to:

```
window.addEventListener('touchmove', function(event) {
    if(event.target.type !== 'textarea') {
        event.preventDefault();
    }
}, true);
```

This will probably not work for scrollviews, but it's a quick fix for my project.

It works in this fiddle, where i override the touchmove listener: http://jsfiddle.net/w9xw8fhz/1/

InputSurfaces also can't be scrolled, my fix doesn't work for that though.

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive and spirit to the famous engine, which can be found at --> http://github.com/famous/engine
