### ISSUE TITLE
GenericSync public addSync function does not add options

### ISSUE THREAD

**Issue by etyp** [Famous/famous#668]
When trying to customize Scrollview.js so that multiple users can concurrently use multiple scrollviews, I tried setting a touchLimit option on the scrollview's GenericSync only to find the options weren't being set.

`GenericSync.prototype.addSync = function addSync(syncs) {...}`

Does not set options directly, yet the private `_addSingleSync` function does:

`function _addSingleSync(key, options) {...}`

I've added an `options` parameter on the `addSync` function and it's working as expected now. Not sure if this was intentional or not, but as far as I can see it could be an issue.

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive and spirit to the famous engine, which can be found at --> http://github.com/famous/engine
