### ISSUE TITLE
Reference documentation site extremely slow and unreliable

### ISSUE THREAD

**Issue by rbabayoff** [Famous/famous#670]
Half of the times I'm trying to get to it, it doesn't load, and the other half, it loads slowly.

**Comment by jd-carroll** [comment]
You are almost better off taking a look at stackoverflow.  Not that I am trying to drive traffic away from famo.us, but some of the answers there are really pretty extensive.

But, to respond to your problem, which site specifically are you having problems with?  (Or what documentation?)

**Comment by rbabayoff** [comment]
This one:

http://famo.us/docs/reference/

It seems it's being served from different servers than the main web site. Always problems loading pages there.

**Comment by MylesBorins** [comment]
The reference docs should be sitting behind our CDN layer.  I’m going to check with ops on this.

Best,

Myles Borins

Head of Labs and Developer Advocacy

**Comment by MylesBorins** [comment]
This is due to the github DDOS... should return to normal eventually.  Sorry for the frustration.
