### ISSUE TITLE
API documentation should include hash links from property / method names to their documentation

### ISSUE THREAD

**Issue by rbabayoff** [Famous/famous#671]
Makes you waste a lot of time not having that, needing to scroll down to method name description.

**Comment by jd-carroll** [comment]
Could you create a PR example for one such hash link?

**Comment by rbabayoff** [comment]
Your API docs are auto rendered using JSDoc, according to your web site. I'm sure there's a switch that allows you to do that. For an example of how it is now:

http://famo.us/docs/api/latest/events/EventArbiter

Just try and click on the red method name, i.e. setMode, and it's not a link (even though it looks like a link).

**Comment by MylesBorins** [comment]
This is unfortunately a won't fix for the time being.  Expect an entirely new documentation site in the future which will solve all of these problems.
