### ISSUE TITLE
`surface.setContent` does not do anything when the surface is removed from the DOM in the next render-cycle

### ISSUE THREAD

**Issue by IjzerenHein** [Famous/famous#673]
When you call `surface.setContent` it sets both `this.content` and `this._contentDirty` on the Surface. In the next `commit` it is then deployed to the DOM. However, when in the next render-cycle, the surface is not committed, but instead recalled, the value set by `setContent` is overridden by `surface.recall`. Later, when the surface is commited again and added to the DOM, not the last value set by `setContent` is shown, but instead the last DOM content is shown. This is a problem in the `recall` function which should deal with the `_contentDirty` case in some way.

Original code:

``` javascript
Surface.prototype.recall = function recall(target) {
  var df = document.createDocumentFragment();
  while (target.hasChildNodes()) df.appendChild(target.firstChild);
  this.setContent(df);
};
```

Suggested fix:

``` javascript
Surface.prototype.recall = function recall(target) {
  if (!this._contentDirty) {
    var df = document.createDocumentFragment();
    while (target.hasChildNodes()) df.appendChild(target.firstChild);
    this.setContent(df);
  }
};
```

I've tested it in my own environment and works perfectly. I'll create a pull request for it as well.

Cheers,
Hein

**Comment by jd-carroll** [comment]
So I'm a little confused by this... Why would you ever want to prevent a `Surface` from being recalled?  It shouldn't matter if the surface is dirty or not, it is being recalled.  

Can you please provide a little more context behind this.  I think placing any conditions on the recall will introduce more problems than it could potentially solve.  (But maybe I'm wrong)

**Comment by IjzerenHein** [comment]
Hi, I'll provide a test case, so you can see the problem in action. It will probably make sense then.
But I agree completely with your sentiment, introducing unnecessary conditions should be avoided at all cost.

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive and spirit to the famous engine, which can be found at --> http://github.com/famous/engine
