### ISSUE TITLE
Is Famous  really useful for developing a Hybrid mobile application?

### ISSUE THREAD

**Issue by amitchoubey** [Famous/famous#675]
I am trying to develop a Hybrid Mobile application using Famous with some 3D animations.
But application is not working smooth how its working in chrome browser.
Application which I am developing using Famous & Phonegap its only working properly in higher devices like Moto-g & Nexus Google based devices.
its only supports and works properly in that devices where chrome is a default browser in mobile.

My question is only that "Is Famous is really useful for developing a Hybrid mobile application as of now"?

**Comment by MylesBorins** [comment]
Have you tried using crosswalk?  For older devices you want to use a pluggable webview

**Comment by amitchoubey** [comment]
@TheAlphaNerd can you please share little Idea about "crosswalk" & "pluggable webview" with me.
And issue is not only related to lover devices, also not working in Samsung Galaxy 5 or Android version Kitkat. basically its works smoothly only in that mobile where chrome is default browser not android browser.

**Comment by markmarijnissen** [comment]
The answer is YES, it is really useful.

And yes, you should use Crosswalk. [I can google that for you](http://lmgtfy.com/?q=crosswalk). It allows you to bundle the latest & newest chrome browser with your app for fast performance. Because even when the browser is only a few versions behind, it'll make huge difference in performance.

**Comment by amitchoubey** [comment]
@markmarijnissen & @TheAlphaNerd Thank's for the reply I will try & test.

**Comment by particle4dev** [comment]
@amitchoubey what result after using crosswalk ? Can you share with us ? Thanks

**Comment by amitchoubey** [comment]
@particle4dev I was tried to add crosswalk in eclipse but some crosswalk error was occurring so for time being issue I skipped  it for some time but I will try & tell you the result soon.

**Comment by amitchoubey** [comment]
@particle4dev Finally got a result for famo.us with crosswalk & now 3d animations are working properly not that much smooth in mobile devices if we compare with desktop chrome browser.
But if we reduce animation frames then hopefully works fine in mobile devices also.
@TheAlphaNerd  & @markmarijnissen thank's to both of you that you guys shared idea about crosswalk.

**Comment by particle4dev** [comment]
@amitchoubey Thanks, it very helpful :) I also was trying to use crosswalk in my app yesterday but did not succeed. Can you share with me some tutorial or document about crosswalk?

**Comment by amitchoubey** [comment]
@particle4dev You can try Intel XDK which is very easier to build crosswalk mobile app.
I am sharing some links with you so that you can download & read also.
https://software.intel.com/en-us/intel-xdk
https://software.intel.com/en-us/xdk/docs/crosswalk-application-runtime-overview
http://code.tutsplus.com/articles/getting-started-with-intel-xdk--cms-22205
