### ISSUE TITLE
backgroundColor

### ISSUE THREAD

**Issue by adriano-di-giovanni** [Famous/famous#676]
Given a view with its subviews, I'd like to have a background color set on the view to take advantage of transparent subviews. How to do it?

**Comment by adriano-di-giovanni** [comment]
ContainerSurface. Right?

**Comment by kemalettin46** [comment]
Next I'm going to hit on the way <a href="http://youjizz.bz">youjizz</a> out of kindred and the use of the n-expression term. I'm inky and I'm bonny mitigative on the n expression term.

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive and spirit to the famous engine, which can be found at --> http://github.com/famous/engine
