### ISSUE TITLE
Mobile Interactive Demos

### ISSUE THREAD

**Issue by ghost** [Famous/famous#680]
Hi  I can`t find Mobile Interactive Demos. In main page http://famo.us/demos 404

**Comment by MylesBorins** [comment]
Those demos are no longer available as they were build on version 0.1 of the platform.

**Comment by clockworked247** [comment]
@TheAlphaNerd is there a plan to make an updated set of demos?

**Comment by MylesBorins** [comment]
There will be a new set of examples that will  come out with MixedMode

We are still working towards also having larger demos, but at the moment I cannot make any promises of a timeline on that

**Comment by clockworked247** [comment]
@TheAlphaNerd ok, thanks for the update.

**Comment by bmustata** [comment]
This will be great and a important motivation to use this library.
