### ISSUE TITLE
ScrollView resize not working as expected with [undefined,true] sized surface

### ISSUE THREAD

**Issue by dx9** [Famous/famous#681]
When you resize, the scroll view gets confused. It will under/over scroll based on a smaller/larger resize condition.

http://codepen.io/anon/pen/yymqap?editors=101

Started in famous-angular land https://github.com/Famous/famous-angular/issues/361 

One approach to supporting this case:
1 - Tweak surface to detect relative size changes that impact true sized dimension and schedule corresponding true size checks.
2 - Tweak ScrollView to adjust position based on resize of ViewSequence.Backing in certain cases.

Not sure if the approach is sound.

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive and spirit to the famous engine, which can be found at --> http://github.com/famous/engine
