### ISSUE TITLE
Is there a way to extract and see the current render tree b/c debugging/reporting famo.us without that is bloody hard.

### ISSUE THREAD

**Issue by omasri** [Famous/famous#682]
I am trying to build a prototype app with famo.us and I have to instantiate views and sometimes need to "delete" the views.  "deleting" is doable via the tricks posted on forums

```
    this.node.set({}); or   this.render = function(){ return null; };
```

However, after you delete sometimes something is corrupted b/c other things that used to work don't.  For example, views that used to show and hide via a RenderController. Or many the z-indexing is now behaving unexpectedly.

If we could see or dump it out, then I could at least start to debug and figure out what in the world is going on.  Right now it feels like coding in the dark.

**Comment by omasri** [comment]
I fixed the main delete issue.  Turns out through some bad logic in 1 particular case I would re-add the same view.  Since it would draw on top of the other one I thought there was only 1.

Since the DOM is flat there it is virtually impossible for me to tell.  Making the DOM flat and putting all the nesting in the render tree is great, but it sucks for debugging if we can't see the render tree.

**Comment by MylesBorins** [comment]
Hye @omasri currently we do not have any tools for creating the render tree, perhaps that could be a fun project to work on.

**Comment by omasri** [comment]
Yes it would be.  I was chatting to a friend and he was keen on making a nice chrome extension.  Do you have a code snipet on how to traverse the tree from a main context?
