### ISSUE TITLE
Very bad performance for ScrollView on Android/Cordova

### ISSUE THREAD

**Issue by mutazmq** [Famous/famous#685]
Please watch this [video](https://www.youtube.com/watch?v=EwkflvyEbtE)
My device is Galaxy S4, Android 4.4.2. App packaged by Cordova.
I copied the phone app example on Famo.us website and just added ScrollView to its PageView. However, and even though ScrollView has no content still, the performance is very disappointing.

I also tried scrolling on Chrome browser installed on my device. There is some performance gain but it is still noticeably lagging.

Any idea? Thanks

**Comment by MylesBorins** [comment]
Are you using fastclick? Have you tried building with crosswalk?

**Comment by mutazmq** [comment]
I am using fastclick. There is some performance gain when I commented it out, but still in Cordova it is lagging. 
About crosswalk, I used latest version of Chrome on my device instead. Performance still bad (with fastclick commented out).

**Comment by mutazmq** [comment]
Do you think I can get over this issue? 
Another question, is Famous actively developed? I don't see any activity recently.

Thanks

**Comment by MylesBorins** [comment]
@mutazmq the public version is not currently actively developed. Our resources have been put towards MixedMode a new version of the platform that will be released in conjunction with jQuerySF

**Comment by MylesBorins** [comment]
did you do a build with crosswalk though?

**Comment by amitchoubey** [comment]
@TheAlphaNerd can you please make any example of application with crosswalk & cordova or phonegap using famo.us and can you please share it with us.

**Comment by dcsan** [comment]
@mutazmq how does that view work just in the chrome browser, ie not a cordova app? chrome the browser is definitely using a "chrome webview". 
you could also try to get a stock AOSP browser to see if it's a browser rendering engine issue or a famous problem.

> I also tried scrolling on Chrome browser installed on my device. There is some performance gain but it is still noticeably lagging.

right. so it's a problem with famous

in my experience too even on the latest samsung devices the famous scrollview is jerky and unusable and probably responsible for turning lots of people off famous. 
hopefully mixed mode will deliver something better.

**Comment by mutazmq** [comment]
@dcsan I guess that the webview Chrome uses is an updated version than my android one. I'm not sure though. I just visually noticed a performance gain.
Anyway, I stopped playing with famous and awaiting mixed mode. Back to native for now!!

**Comment by MylesBorins** [comment]
Hey all, I'm closing this issue.  If you would like to continue the discussion please come to teh famous community-slack

http://slack.famous.org

you can signuup at http://slack.famous.org/signup
