### ISSUE TITLE
whats happening?

### ISSUE THREAD

**Issue by dcsan** [Famous/famous#686]
just wondering what's going on with this progress? it seems like since the big fundraising, there's no public activity for the last 3 months? I guess you're probably not going to make an announcement on github but it would be good to know if the project is dead or not. maybe you're rewriting everything for a webGL future version, or someone is in talks to acquire the company, other things you can't announce. but it would be nice to know if the project should be avoided in its current state, or not.

![image](https://cloud.githubusercontent.com/assets/514002/7276048/35956e86-e8bc-11e4-98c1-4a1d3ebac0d3.png)

**Comment by talves** [comment]
@dcsan I tweeted about a webcast. [Steve makes a crazy announcement about Open Source License for Mixed Mode!](https://twitter.com/3_Alves/status/591267629379104769)

**Comment by MylesBorins** [comment]
hey @dcsan I'm sorry that things have not been so transparent lately, we have been heads down and not been great with letting the community know what's up.

We have almost all of our internal resources working full time on MixedMode so we can get it out the door. In the past I had been spending quite a bit of time keeping this version of the platform moving, albeit slowly. After taking on the responsibility of curating jQuerySF I have just not had the time to dedicate.

I genuinely apologize for not being better at keeping this target moving. It is a very hard to decide where to put time and resources. I take the responsibility of maintaining a project like this very seriously, and want you to know that we would not have gone dark in the way we have if it wasn't necessary for us to move forward.

**Comment by talves** [comment]
@TheAlphaNerd :+1: for putting time into getting MixedMode out the door and into the wild as possible.

**Comment by BodhiHu** [comment]
For those hoping to get the latest news of famous, can follow Steve Newcomb's twitter: https://twitter.com/stevenewcomb.

Anyway famo.us just felt to be the right way to create native like apps in HTML5, in an intuitive level.

**Comment by talves** [comment]
@ShawnOceanHu been following him since launch.  Is there news that I missed?

**Comment by BodhiHu** [comment]
@talves in that case I think not

**Comment by jmeiss** [comment]
Following Steve announcement, do you have any information about upgrading from famo.us 0.3 to 0.4?

**Comment by talves** [comment]
@jmeiss https://github.com/Famous/famous/issues/692#issuecomment-98848980

**Comment by MylesBorins** [comment]
Oh.. mixed mode is out.

http://github.com/famous/engine
