### ISSUE TITLE
ScrollView breaks when surface content is modified by a third party like Angular.

### ISSUE THREAD

**Issue by dx9** [Famous/famous#687]
Note this happens with #684 applied. Similar symptoms different cause.

Hit this using ng-include. Pen uses ng-bind-html. http://codepen.io/anon/pen/YXzZbV?editors=101

Could be a case of don't do that silly! Looking at options for syncing state to improve automagic.

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive and spirit to the famous engine, which can be found at --> http://github.com/famous/engine
