### ISSUE TITLE
Using ViewSequence.splice can mess up the internal linked-list

### ISSUE THREAD

**Issue by IjzerenHein** [Famous/famous#689]
When using ViewSequence.splice, the internal linked-list can get messed up, causing the ViewSequence to return the duplicate nodes when iterating the view-sequence.

I've boiled it down to this minimal example causing problems:

``` javascript
var viewSequence = new ViewSequence();
viewSequence.splice(0, 0, new Surface({content: 'surface 1'}));
viewSequence.splice(1, 0, new Surface({content: 'surface 2'}));
viewSequence.push(new Surface({content: 'surface 3'}));
```

When iterating the view-sequence, you would expect the view-sequence to contain 3 nodes, surface 1, 2 and 3. But instead, using getNext to enumerate the view-sequence yields:

```
surface 1
surface 2
surface 2
surface 3
```

I've included a live demo showcasing the problem here: http://gloey.nl/apps/ViewSequence/
When you check the console, you will see the faulty output.
The code is hosted here: https://github.com/IjzerenHein/famous-playground/blob/viewSequence/app/main.js

I'm going to investigate the problem further and keep you posted.

Probably related to #496

**Comment by MylesBorins** [comment]
please try mixed mode
http://github.com/famous/engine
