### ISSUE TITLE
Utility.clone issue

### ISSUE THREAD

**Issue by snowzane** [Famous/famous#694]
`Utility.clone` is used in "core/View.js" and "views/SequentialLayout.js" for initializing options. But many modules using `Object.create` to do this. Is it necessary to use `Utility.clone` ?

**Comment by MylesBorins** [comment]
We are no longer actively maintaining this repo and as such we will not be fixing this.

Thanks you for taking the time to discuss the issue, we hope you will bring the same drive and spirit to the famous engine, which can be found at --> http://github.com/famous/engine
