### ISSUE TITLE
Scroll

### ISSUE THREAD

**Issue by JohnSweedeen** [Famous/famous#699]
how can you make an app where you've got several pictures lined up in in x and y- axis and whenever you scroll to the other picture, wether its the one above or the one beside. It kinda pulls the picture to the middle, so the edges fit, something like gravity to pull these pictures to the middle whenever you scroll and end up having your thumb on the screen with half of the picture on 

( might be hard to understand ) 

in a regular scrolling app. It keeps on scrolling untill it stops by itself, but for an example lets say in my contacts i want to scroll but i want it to feel like (chatt roulette - machine kinda of) it stops harder for ever scrolling contact. maybe something like gravity to pull against the scrolling direction

**Comment by dcsan** [comment]
better to make a quick layout diagram with google drawings and embed it here.
also check out famous-flex https://github.com/IjzerenHein/famous-flex

**Comment by MylesBorins** [comment]
please try mixed mode
http://github.com/famous/engine
