### ISSUE TITLE
mixed mode - native overflow scrolling with famous (+flex view)

### ISSUE THREAD

**Issue by dcsan** [Famous/famous#701]
the awesome famous-flex views are a huge step up from famous own scrollviews but still chug compared to a normal browser or native scrolling.

the best of both worlds would be to be able to integrate normal native scrolling within a div using `overflow-y scroll`.  

I made a test of this, but get very odd results - sometimes it scrolls and sometimes not. dunno why.

http://famous-appmode.meteor.com/story/1

The other pages there with lots of small divs are using [famous-flex](https://github.com/IjzerenHein/famous-flex) and actually the performance isn't that bad.

If I used the `appMode: false` flag, this would break other things like famous headers and footers. there maybe a way to workaround that with `position: fixed` and limiting the famous view to the viewport area and `overflow: hidden`, but this is piling lots of CSS hacks on top of each other.

Has anyone else come up with a way to mix these two modes?

It would make famous so much more useful if i could combine it with a normal web app, with a little adjustment, to at least give the basic level of experience we expect from a browser, even if not quite a native app.

**Comment by kakajansh** [comment]
It is not scrolling because you have invisible surface on top [here](https://github.com/dcsan/flowwy/blob/appmode/app/client/views/stories/one/StoryOneView.coffee#L12)

You need to add `zIndex: -1` property to your back surface and

```
  modifier = new StateModifier
    origin: [0.5, 0.5]
    align: [0.5, 0.5]
    transform: Transform.translate(0,0,-1)
```

**Comment by dcsan** [comment]
OK I got this basically working here

http://moflow.meteor.com/story/12

this view nests a normal native scrolling html content inside a famous app

![image](https://cloud.githubusercontent.com/assets/514002/7693643/58ea6792-fd89-11e4-9658-1004e8b83b19.png)

it also uses famous-flex for the other type of famous views.
It's a basic framework for creating usable famous apps and working around the problems with their scrollviews.

with @sayawan we may add some other components to this.  repo is here:
https://github.com/dcsan/moflow

I invite people to check it out - smooth even on an android device.
http://moflow.meteor.com/story/12

**Comment by BodhiHu** [comment]
@dcsan awesome work !

**Comment by MylesBorins** [comment]
hey all. We are closing this isssue as this repo is no longer being worked on. It might make sense to continue the discussion in the famous community slack

http://slack.famous.org

signup --> http://slack.famous.org/signup
