### ISSUE TITLE
dev console and CTRL+C

### ISSUE THREAD

**Issue by alfondotnet** [Famous/famous#708]
Am I missing something here (probably), or would this be helpful in the generated `bin/dev.js`

```
process.on('SIGINT', function() {
    process.exit();
});
```

To gracefully close the process?

Cheers!, loving famous!

**Comment by alexanderGugel** [comment]
This won't work on Windows. You would have to use [`readline`'s](https://nodejs.org/api/readline.html#readline_event_sigint) `SIGINT` event if you really want to do this.

**Update** Sorry, just saw this has been closed.
**Update 2** This is also probably not the repo you're looking for. The new seed project, including the `dev.js` file is in [Famous/engine-seed](https://github.com/Famous/engine-seed).

**Comment by alfondotnet** [comment]
Yep thanks, that's why I closed the issue :-)
