### ISSUE TITLE
Scrolling problem when height of blocks is less than container height (stuck at the bottom)

### ISSUE THREAD

**Issue by extempl** [Famous/famous#709]
Hey guys, I know that this was deprecated. But I've had a luck to build one of the projects on 0.3 version, and now I need to maintain it.

I have a problem, when scrolled blocks stuck at the bottom of container if summary height is less than container height. You can see it on the screencast: http://screencast.com/t/fRynNWRuQ5oJ

I'd appreciate any kind of help. 
Maybe someone can, at least, advice where I need to set breakpoint to determine the problem.

**Comment by extempl** [comment]
Seems like the problem is in [this block](https://github.com/Famous/famous/blob/develop/src/views/Scroller.js#L266) since it sending wrong position (non-zero) which is assigned to `this._edgeSpringPosition` but I'm still not sure what I need to do to get correct behaviour...

**Comment by MylesBorins** [comment]
@extempl we are no longer maintaining this repo. I highly suggest patching this file and including the replacement directly in your project.
