### ISSUE TITLE
Infinite scroll view

### ISSUE THREAD

**Issue by kof** [Famous/famous#73]
I have several questions:
1. Currently it requires creating a Surface for every item every time. Does surface every time create a dom element? So potentially infinite amount of dom elements will be created?
2. After a user has scrolled down lots of pages, at some point famous needs to start cleaning up the surfaces list in terms of memory management. Is this planned?
3. Functionality like "offset" etc. should be actually a part of famous( @JonnyBGod has created a wrapper already https://github.com/JonnyBGod/famous-infinitescroll)

**Comment by mutazmq** [comment]
As the user scrolls down, I need an event to be triggered to tell me that the ScrollView has almost reach an end and I need to add a new set of surfaces. Currently, I don't see any event or handler that helps me to do so. What is the best way to implement it?
