### ISSUE TITLE
React.js integration

### ISSUE THREAD

**Issue by jbremmer** [Famous/famous#82]
I wonder if React.js integration is in the works and what possible direction it's taking.

I've glanced over https://github.com/petehunt/famous-react but seems far from good enough to start on and literally no info there.

Having those two would offer folks really strong tool.

Even some guidance on how to use react as content provider to Surface would be helpful to most of the folks.

**Comment by Kinnardian** [comment]
:((

**Comment by tiye** [comment]
@Kinnardian check this repo for updates: https://github.com/pilwon/react-famous/graphs/contributors
