### ISSUE TITLE
[question] how do I know if my view or surface is in the render tree?

### ISSUE THREAD

**Issue by kof** [Famous/famous#85]
Hi

The reason why I need to know that is because I do some calculations on an event. This event continues firing the whole time and there is no need to calculate anything if my view/surface is not in the render tree.

**Comment by jacksenechal** [comment]
A year later, just wondering what became of the work in progress on this? Are surfaces able to understand whether they are on the screen or not? If so, is it available in the 0.3 library, or just the new engine?

**Comment by michaelobriena** [comment]
@jacksenechal development on this repository stopped many months ago.  If you go to github.com/Famous/engine you can see the newer rendering engine.

That said, this is not a feature we implemented because we feel the use cases are really small and there are better uses of our time.
